const words = {};

words.en = [
    { text: 'grandma', category: 'Family' },
    { text: 'grandpa', category: 'Family' },
    { text: 'husband', category: 'Family' },
    { text: 'parents', category: 'Family' },
    { text: 'wife', category: 'Family' },
    { text: 'uncle', category: 'Family' },
    { text: 'aunt', category: 'Family' },
    { text: 'father', category: 'Family' },
    { text: 'mother', category: 'Family' },
    { text: 'step sister', category: 'Family' },
    { text: 'step brother', category: 'Family' },
    { text: 'step father', category: 'Family' },
    { text: 'step mother', category: 'Family' },
    { text: 'god father', category: 'Family' },
    { text: 'god mother', category: 'Family' },
    { text: 'mother in law', category: 'Family' },
    { text: 'father in law', category: 'Family' },
    { text: 'children', category: 'Family' },
    { text: 'brother', category: 'Family' },
    { text: 'sister', category: 'Family' },
    { text: 'cousin', category: 'Family' },
    { text: 'granddaugther', category: 'Family' },
    { text: 'grandson', category: 'Family' },
    { text: 'niece', category: 'Family' },
    { text: 'nephew', category: 'Family' },

    { text: 'festivus', category: 'Festivity' },
    { text: 'hanukkah', category: 'Festivity' },
    { text: 'kwanzaa', category: 'Festivity' },
    { text: 'wedding', category: 'Festivity' },
    { text: 'birthday', category: 'Festivity' },
    { text: 'bar mitzvah', category: 'Festivity' },
    { text: 'halloween', category: 'Festivity' },
    { text: 'octoberfest', category: 'Festivity' },
    { text: 'christmas', category: 'Festivity' },
    { text: 'Día de Muertos', category: 'Festivity' },
    { text: 'new year`s eve', category: 'Festivity' },
    { text: 'groundhog day', category: 'Festivity' },
    { text: 'Valentine`s Day', category: 'Festivity' },
    { text: 'St. Patrick`s Day', category: 'Festivity' },
    { text: 'passover', category: 'Festivity' },
    { text: 'easter', category: 'Festivity' },
    { text: 'Ramadan', category: 'Festivity' },
    { text: 'Mother`s Day', category: 'Festivity' },
    { text: 'Independence Day', category: 'Festivity' },
    { text: 'Columbus Day', category: 'Festivity' },
    { text: 'Divali', category: 'Festivity' },
    { text: 'Black Friday', category: 'Festivity' },
    { text: 'thanks giving', category: 'Festivity' },
    { text: 'election', category: 'Festivity' },
    { text: 'Graduation', category: 'Festivity' },

    { text: 'bracelet', category: 'Valuables' },
    { text: 'crystal', category: 'Valuables' },
    { text: 'diamond', category: 'Valuables' },
    { text: 'emerald', category: 'Valuables' },
    { text: 'jewelry', category: 'Valuables' },
    { text: 'gold bar', category: 'Valuables' },
    { text: 'pearls', category: 'Valuables' },

    { text: 'bromance', category: 'Social' },
    { text: 'follower', category: 'Social' },
    { text: 'highfive', category: 'Social' },
    { text: 'marriage', category: 'Social' },
    { text: 'divorce', category: 'Social' },
    { text: 'frenemy', category: 'Social' },

    { text: 'hulahoop', category: 'Games' },
    { text: 'pinwheel', category: 'Games' },
    { text: 'swingset', category: 'Games' },
    { text: 'balloon', category: 'Games' },
    { text: 'dreidel', category: 'Games' },
    { text: 'gameboy', category: 'Games' },

    { text: 'pinball', category: 'Games' },
    { text: 'checkers', category: 'Games' },
    { text: 'joystick', category: 'Games' },
    { text: 'monopoly', category: 'Games' },
    { text: 'scrabble', category: 'Games' },
    { text: 'yahtzee', category: 'Games' },

    { text: 'Chair', category: 'Furniture' },
    { text: 'barstool', category: 'Furniture' },
    { text: 'bookcase', category: 'Furniture' },
    { text: 'waterbed', category: 'Furniture' },
    { text: 'bathtub', category: 'Furniture' },
    { text: 'bunkbed', category: 'Furniture' },
    { text: 'cabinet', category: 'Furniture' },
    { text: 'dresser', category: 'Furniture' },
    { text: 'Bed', category: 'Furniture' },

    { text: 'chainsaw', category: 'Tool' },
    { text: 'scissors', category: 'Tool' },
    { text: 'tweezers', category: 'Tool' },
    { text: 'compass', category: 'Tool' },
    { text: 'crowbar', category: 'Tool' },
    { text: 'dustpan', category: 'Tool' },
    { text: 'stapler', category: 'Tool' },

    { text: 'lipstick', category: 'Toiletries' },
    { text: 'perfume', category: 'Toiletries' },
    { text: 'shampoo', category: 'Toiletries' },
    { text: 'nailfile', category: 'Toiletries' },
    { text: 'sunblock', category: 'Toiletries' },
    { text: 'hairdye', category: 'Toiletries' },
    { text: 'hairgel', category: 'Toiletries' },
    { text: 'mascara', category: 'Toiletries' },

    { text: 'computer', category: 'Computing' },
    { text: 'facebook', category: 'Computing' },
    { text: 'firewall', category: 'Computing' },
    { text: 'keyboard', category: 'Computing' },
    { text: 'password', category: 'Computing' },
    { text: 'hashtag', category: 'Computing' },
    { text: 'macbook', category: 'Computing' },
    { text: 'twitter', category: 'Computing' },

	{ category: 'Weapon', text: 'Battle Axe' },
	{ category: 'Weapon', text: 'bayonet' },
	{ category: 'Weapon', text: 'bazooka' },
	{ category: 'Weapon', text: 'cannon' },
	{ category: 'Weapon', text: 'catapult' },
	{ category: 'Weapon', text: 'crossbow' },
	{ category: 'Weapon', text: 'dynamite' },
	{ category: 'Weapon', text: 'handgun' },
	{ category: 'Weapon', text: 'missile' },
	{ category: 'Weapon', text: 'shotgun' },
	{ category: 'Weapon', text: 'Sword' },
	{ category: 'Weapon', text: 'torpedo' },
	{ category: 'Weapon', text: 'Warhammer'},

    { text: 'eyepatch', category: 'Accessory' },
    { text: 'headband', category: 'Accessory' },
    { text: 'kneepads', category: 'Accessory' },
    { text: 'necklace', category: 'Accessory' },
    { text: 'nosering', category: 'Accessory' },
    { text: 'partyhat', category: 'Accessory' },
    { text: 'shoelace', category: 'Accessory' },
    { text: 'umbrella', category: 'Accessory' },
    { text: 'bandana', category: 'Accessory' },
    { text: 'earring', category: 'Accessory' },
    { text: 'hairtie', category: 'Accessory' },
    { text: 'handbag', category: 'Accessory' },
	{ category: 'Accessory', text: 'Handkerchief' },

    { category: 'Clothing', text: 'Chasity Belt' },
    { category: 'Clothing ', text: 'Tophat' },
    { category: 'Clothing', text: 'pantsuit' },
    { category: 'Clothing', text: 'bandana' },
    { category: 'Clothing', text: 'belt' },
    { category: 'Clothing', text: 'bikini' },
    { category: 'Clothing', text: 'boots' },
    { category: 'Clothing', text: 'bowtie' },
	{ category: 'Clothing', text: 'Tophat' },
	{ category: 'Clothing', text: 'Cowboy Hat' },
    { category: 'Clothing', text: 'cap' },
    { category: 'Clothing', text: 'coat' },
    { category: 'Clothing', text: 'dress' },
    { category: 'Clothing', text: 'earmuffs' },
    { category: 'Clothing', text: 'eyepatch' },
    { category: 'Clothing', text: 'glasses' },
    { category: 'Clothing', text: 'gloves' },
    { category: 'Clothing', text: 'hairtie' },
	{ category: 'Clothing', text: 'Hoodie' },
    { category: 'Clothing', text: 'hat' },
    { category: 'Clothing', text: 'headband' },
    { category: 'Clothing', text: 'jacket' },
    { category: 'Clothing', text: 'jeans' },
    { category: 'Clothing', text: 'kneepads' },
    { category: 'Clothing', text: 'mittens' },
    { category: 'Clothing', text: 'necklace' },
    { category: 'Clothing', text: 'overalls' },
    { category: 'Clothing', text: 'pajamas' },
    { category: 'Clothing', text: 'partyhat' },
    { category: 'Clothing', text: 'raincoat' },
    { category: 'Clothing', text: 'sandals' },
    { category: 'Clothing', text: 'scarf' },
    { category: 'Clothing', text: 'shirt' },
    { category: 'Clothing', text: 'shoes' },
    { category: 'Clothing', text: 'skirt' },
    { category: 'Clothing', text: 'slippers' },
    { category: 'Clothing', text: 'sneakers' },
    { category: 'Clothing', text: 'socks' },
    { category: 'Clothing', text: 'sombrero' },
    { category: 'Clothing', text: 'stockings' },
    { category: 'Clothing', text: 'suit' },
    { category: 'Clothing', text: 'sweater' },
    { category: 'Clothing', text: 'sweatshirt' },
    { category: 'Clothing', text: 'swimsuit' },
    { category: 'Clothing', text: 't-shirt' },
    { category: 'Clothing', text: 'tie' },
    { category: 'Clothing', text: 'trousers' },
    { category: 'Clothing', text: 'underpants' },

    { text: 'crutches', category: 'Medical' },
    { text: 'dandruff', category: 'Medical' },
    { text: 'dentures', category: 'Medical' },
    { text: 'firstaid', category: 'Medical' },
    { text: 'headache', category: 'Medical' },
    { text: 'hospital', category: 'Medical' },
    { text: 'insomnia', category: 'Medical' },
    { text: 'medicine', category: 'Medical' },
    { text: 'papercut', category: 'Medical' },
    { text: 'seasick', category: 'Medical' },
    { text: 'sunburn', category: 'Medical' },
    { text: 'vaccine', category: 'Medical' },
    { text: 'vitamin', category: 'Medical' },

    { text: 'hongkong', category: 'Geography' },
    { text: 'scotland', category: 'Geography' },
    { text: 'america', category: 'Geography' },
    { text: 'atlanta', category: 'Geography' },
    { text: 'bahamas', category: 'Geography' },
    { text: 'england', category: 'Geography' },
    { text: 'finland', category: 'Geography' },
    { text: 'florida', category: 'Geography' },
    { text: 'germany', category: 'Geography' },
    { text: 'holland', category: 'Geography' },
    { text: 'ireland', category: 'Geography' },
    { text: 'jamaica', category: 'Geography' },
    { text: 'new-york', category: 'Geography' },
    { text: 'orlando', category: 'Geography' },

    { text: 'Cabbage', category: 'Plant' },
    { text: 'Persimmon', category: 'Plant' },
    { text: 'Cucumber', category: 'Plant' },
    { text: 'Zucchini', category: 'Plant' },
    { text: 'Watermelon', category: 'Plant' },
    { text: 'Mango', category: 'Plant' },
    { text: 'Lemon', category: 'Plant' },
    { text: 'Lime', category: 'Plant' },
    { text: 'Potato', category: 'Plant' },
    { text: 'Cactus', category: 'Plant' },
    { text: 'Tomato', category: 'Plant' },
    { text: 'Eggplant', category: 'Plant' },
    { text: 'Palmtree', category: 'Plant' },
    { text: 'Pinecone', category: 'Plant' },
    { text: 'Pinetree', category: 'Plant' },
    { text: 'Primrose', category: 'Plant' },
    { text: 'Oak', category: 'Plant' },
    { text: 'Seaweed', category: 'Plant' },
    { text: 'Bamboo', category: 'Plant' },
    { text: 'Carrot', category: 'Plant' },
    { text: 'Celery', category: 'Plant' },
    { text: 'Cherry', category: 'Plant' },
    { text: 'Garlic', category: 'Plant' },
    { text: 'Grapes', category: 'Plant' },
    { text: 'Cilantro', category: 'Plant' },
    { text: 'Banana', category: 'Plant' },
    { text: 'Broccoli', category: 'Plant' },
    { text: 'Avocado', category: 'Plant' },
    { text: 'Coconut', category: 'Plant' },
    { text: 'Peaches', category: 'Plant' },
    { text: 'Spinach', category: 'Plant' },
    { text: 'Pineapple', category: 'Plant' },
    { text: 'Wheat', category: 'Plant' },
    { text: 'Orange', category: 'Plant' },

    { text: 'backbone', category: 'Anatomy' },
    { text: 'forehead', category: 'Anatomy' },
    { text: 'mustache', category: 'Anatomy' },
    { text: 'nosehair', category: 'Anatomy' },
    { text: 'shoulder', category: 'Anatomy' },
    { text: 'skeleton', category: 'Anatomy' },
    { text: 'tentacle', category: 'Anatomy' },
    { text: 'whiskers', category: 'Anatomy' },
    { text: 'eyeball', category: 'Anatomy' },
    { text: 'eyebrow', category: 'Anatomy' },
    { text: 'eyelash', category: 'Anatomy' },
    { text: 'kneecap', category: 'Anatomy' },
    { text: 'knuckle', category: 'Anatomy' },
    { text: 'stomach', category: 'Anatomy' },
    { text: 'unibrow', category: 'Anatomy' },

    { category: 'Location', text: 'Airport' },
    { category: 'Location', text: 'Apartment Building' },
    { category: 'Location', text: 'Bank' },
    { category: 'Location', text: 'Barber Shop' },
	{ category: 'Location', text: 'Bar' },
    { category: 'Location', text: 'Barn' },
	{ category: 'Location', text: 'Beach' },
    { category: 'Location', text: 'Book Store' },
    { category: 'Location', text: 'Bowling Alley' },
    { category: 'Location', text: 'Bus Stop' },
	{ category: 'Location', text: 'Casino' },
    { category: 'Location', text: 'Cathedral' },
	{ category: 'Location', text: 'Castle' },
	{ category: 'Location', text: 'Cemetery' },
	{ category: 'Location', text: 'Church' },
	{ category: 'Location', text: 'Circus' },
    { category: 'Location', text: 'Convenience Store' },
    { category: 'Location', text: 'Courthouse' },
	{ category: 'Location', text: 'Desert' },
    { category: 'Location', text: 'Department Store' },
    { category: 'Location', text: 'Disco' },
	{ category: 'Location', text: 'Dungeon' },
    { category: 'Location', text: 'Fire Station' },
	{ category: 'Location', text: 'Garden' },
    { category: 'Location', text: 'Gas Station' },
	{ category: 'Location', text: 'Golf Course' },
    { category: 'Location', text: 'Hospital' },
    { category: 'Location', text: 'House' },
	{ category: 'Location', text: 'Library' },
    { category: 'Location', text: 'Lighthouse' },
	{ category: 'Location', text: 'Mansion' },
    { category: 'Location', text: 'Mall' },
    { category: 'Location', text: 'Movie Theater' },
    { category: 'Location', text: 'Museum' },
    { category: 'Location', text: 'Office Building' },
    { category: 'Location', text: 'Opera House' },
	{ category: 'Location', text: 'Orchard' },
    { category: 'Location', text: 'Palace' },
	{ category: 'Location', text: 'Petshop' },
    { category: 'Location', text: 'Police Station' },
    { category: 'Location', text: 'Post Office' },
	{ category: 'Location', text: 'Prison' },
	{ category: 'Location', text: 'Pub' },
    { category: 'Location', text: 'Restaurant' },
	{ category: 'Location', text: 'Safari' },
    { category: 'Location', text: 'Saw Mill' },
	{ category: 'Location', text: 'School' },
	{ category: 'Location', text: 'Skyscraper' },
    { category: 'Location', text: 'Supermarket' },
	{ category: 'Location', text: 'Swimming Pool' },
    { category: 'Location', text: 'Temple' },
    { category: 'Location', text: 'Train Station' },
	{ category: 'Location', text: 'Theater' },
	{ category: 'Location', text: 'Theme Park' },
	{ category: 'Location', text: 'Vet Clinic' },
	{ category: 'Location', text: 'Zoo' },

    { text: 'Airplane', category: 'Transportation' },
    { text: 'Bicycle', category: 'Transportation' },
	{ text: 'Bus', category: 'Transportation' },
	{ text: 'Boat', category: 'Transportation' },
    { text: 'Dog Sled', category: 'Transportation' },
	{ text: 'Double Decker bus', category: 'Transportation' },
    { text: 'F-16', category: 'Transportation' },
    { text: 'Forklift', category: 'Transportation' },
    { text: 'Formula One', category: 'Transportation' },
    { text: 'Golf Cart', category: 'Transportation' },
    { text: 'Helicopter', category: 'Transportation' },
    { text: 'Hoverboard', category: 'Transportation' },
	{ text: 'Ice Cream Truck', category: 'Transportation' },
    { text: 'Jeep', category: 'Transportation' },
    { text: 'Minivan', category: 'Transportation' },
    { text: 'Ocean Liner', category: 'Transportation' },
    { text: 'Rickshaw', category: 'Transportation' },
    { text: 'Rocketship', category: 'Transportation' },
	{ text: 'Rowboat', category: 'Transportation' },
    { text: 'Sail Soat', category: 'Transportation' },
    { text: 'Scooter', category: 'Transportation' },
    { text: 'Shuttle', category: 'Transportation' },
	{ text: 'Spaceship', category: 'Transportation' },
	{ text: 'Sports Car', category: 'Transportation' },
    { text: 'Stagecoach', category: 'Transportation' },
    { text: 'Steam Boat', category: 'Transportation' },
    { text: 'Submarine', category: 'Transportation' },
    { text: 'Tractor', category: 'Transportation' },
    { text: 'Train', category: 'Transportation' },
	{ text: 'Tram', category: 'Transportation' },
    { text: 'Tow Truck', category: 'Transportation' },
    { text: 'Tricycle', category: 'Transportation' },
    { text: 'Tugboat', category: 'Transportation' },
    { text: 'Unicycle', category: 'Transportation' },
    { text: 'Yacht', category: 'Transportation' },
    { text: 'Zeppelin', category: 'Transportation' },

	{ text: 'AC/DC', category: 'Music Band' },
    { text: 'Adele', category: 'Music Band' },
    { text: 'Beatles', category: 'Music Band' },
    { text: 'Beyonce', category: 'Music Band' },
    { text: 'Billie Eilish', category: 'Music Band' },
    { text: 'Bon Jovi', category: 'Music Band' },
    { text: 'Bruno Mars', category: 'Music Band' },
    { text: 'Childish Gambino', category: 'Music Band' },
    { text: 'Coldplay', category: 'Music Band' },
	{ text: 'David Bowie', category: 'Music Band' },
    { text: 'Daftpunk', category: 'Music Band' },
    { text: 'Dr. Dre', category: 'Music Band' },
    { text: 'Drake', category: 'Music Band' },
    { text: 'Ed Shiran', category: 'Music Band' },
	{ text: 'Elton John', category: 'Music Band' },
    { text: 'Eminem', category: 'Music Band' },
    { text: 'Guns And Roses', category: 'Music Band' },
    { text: 'Jay Z', category: 'Music Band' },
    { text: 'Justin Bieber', category: 'Music Band' },
    { text: 'Justin Timberlake', category: 'Music Band' },
    { text: 'Kanye West', category: 'Music Band' },
    { text: 'Katy Perry', category: 'Music Band' },
    { text: 'Lady Gaga', category: 'Music Band' },
    { text: 'Led Zeppelin', category: 'Music Band' },
    { text: 'Mariah Carey', category: 'Music Band' },
    { text: 'Michael Jackson', category: 'Music Band' },
    { text: 'Muse', category: 'Music Band' },
    { text: 'Nicki Minaj', category: 'Music Band' },
    { text: 'Nirvana', category: 'Music Band' },
    { text: 'Pink Floyd', category: 'Music Band' },
    { text: 'Pitbull', category: 'Music Band' },
    { text: 'Prince', category: 'Music Band' },
    { text: 'Queen', category: 'Music Band' },
    { text: 'Rihana', category: 'Music Band' },
    { text: 'Skrillex', category: 'Music Band' },
    { text: 'Snoop dogg', category: 'Music Band' },
    { text: 'Taylor Swift', category: 'Music Band' },
    { text: 'The Black Eyed Peas', category: 'Music Band' },
    { text: 'Tupac Shakur', category: 'Music Band' },
    { text: 'U2', category: 'Music Band' },

    { text: 'Dubstep', category: 'Music Genre' },
    { text: 'House', category: 'Music Genre' },
    { text: 'Rock', category: 'Music Genre' },
    { text: 'Hip Hop', category: 'Music Genre' },
    { text: 'Blues', category: 'Music Genre' },
    { text: 'Pop', category: 'Music Genre' },
    { text: 'Jazz', category: 'Music Genre' },
    { text: 'Classical', category: 'Music Genre' },
    { text: 'R&B', category: 'Music Genre' },
    { text: 'Heavy Metal', category: 'Music Genre' },
    { text: 'Punk', category: 'Music Genre' },
    { text: 'Country', category: 'Music Genre' },
    { text: 'Reggae', category: 'Music Genre' },
    { text: 'Elevator Music', category: 'Music Genre' },
    { text: 'Disco', category: 'Music Genre' },
    { text: 'Techno', category: 'Music Genre' },
    { text: 'J-Pop', category: 'Music Genre' },
    { text: 'Grunge', category: 'Music Genre' },
    { text: 'Rap', category: 'Music Genre' },
    { text: 'Swing', category: 'Music Genre' },

    { text: 'Bagpipes', category: 'Musical Instrument' },
    { text: 'Bass Guitar', category: 'Musical Instrument' },
    { text: 'Jukebox', category: 'Musical Instrument' },
    { text: 'Trombone', category: 'Musical Instrument' },
    { text: 'Drums', category: 'Musical Instrument' },
    { text: 'Ukulele', category: 'Musical Instrument' },
    { text: 'Electric Guitar', category: 'Musical Instrument' },
    { text: 'Piano', category: 'Musical Instrument' },
    { text: 'Violin', category: 'Musical Instrument' },
    { text: 'Saxophone', category: 'Musical Instrument' },
    { text: 'Cello', category: 'Musical Instrument' },
    { text: 'Flute', category: 'Musical Instrument' },
    { text: 'Clarinet', category: 'Musical Instrument' },
    { text: 'Trumpet', category: 'Musical Instrument' },
    { text: 'Harmonica', category: 'Musical Instrument' },
    { text: 'Harp', category: 'Musical Instrument' },
    { text: 'Banjo', category: 'Musical Instrument' },
    { text: 'Castanets', category: 'Musical Instrument' },
    { text: 'Kazoo', category: 'Musical Instrument' },
    { text: 'Cowbell', category: 'Musical Instrument' },
    { text: 'Cymbal', category: 'Musical Instrument' },
    { text: 'Gong', category: 'Musical Instrument' },
    { text: 'Maraca', category: 'Musical Instrument' },
    { text: 'Marimba', category: 'Musical Instrument' },
    { text: 'Tambourine', category: 'Musical Instrument' },
    { text: 'Triangle', category: 'Musical Instrument' },
    { text: 'Washboard', category: 'Musical Instrument' },
    { text: 'Xylophone', category: 'Musical Instrument' },
    { text: 'Accordion', category: 'Musical Instrument' },
    { text: 'Horn', category: 'Musical Instrument' },
    { text: 'Bugle', category: 'Musical Instrument' },
    { text: 'Didgeridoo', category: 'Musical Instrument' },
    { text: 'Oboe', category: 'Musical Instrument' },
    { text: 'Ocarina', category: 'Musical Instrument' },
    { text: 'Piccolo', category: 'Musical Instrument' },
    { text: 'Whistle', category: 'Musical Instrument' },
    { text: 'Tuba', category: 'Musical Instrument' },
    { text: 'Sitar', category: 'Musical Instrument' },
    { text: 'Fiddle', category: 'Musical Instrument' },
    { text: 'Lute', category: 'Musical Instrument' },

    { text: 'Genie', category: 'Mythology' },
    { text: 'Minotaur', category: 'Mythology' },
    { text: 'Magic Carpet', category: 'Mythology' },
    { text: 'Griffin', category: 'Mythology' },
    { text: 'Minotaur', category: 'Mythology' },
    { text: 'Bigfoot', category: 'Mythology' },
    { text: 'Chimera', category: 'Mythology' },
    { text: 'Cyclop', category: 'Mythology' },
    { text: 'Centaur', category: 'Mythology' },
    { text: 'Mermaid', category: 'Mythology' },
    { text: 'Pegasus', category: 'Mythology' },
    { text: 'Phoenix', category: 'Mythology' },
    { text: 'Unicorn', category: 'Mythology' },
    { text: 'Vampire', category: 'Mythology' },
    { text: 'Dragon', category: 'Mythology' },
    { text: 'Dryad', category: 'Mythology' },
    { text: 'Ghost', category: 'Mythology' },
    { text: 'Medusa', category: 'Mythology' },
    { text: 'Manticore', category: 'Mythology' },
    { text: 'Satyr', category: 'Mythology' },
    { text: 'Sphinx', category: 'Mythology' },
    { text: 'Werewolf', category: 'Mythology' },
    { text: 'Zombie', category: 'Mythology' },
    { text: 'Mummy', category: 'Mythology' },
    { text: 'Golem', category: 'Mythology' },
    { text: 'Amazon Warrior', category: 'Mythology' },
    { text: 'Lizard People', category: 'Mythology' },
    { text: 'Basilisk', category: 'Mythology' },
    { text: 'Goblin', category: 'Mythology' },
    { text: 'Fairy', category: 'Mythology' },
    { text: 'Ghoul', category: 'Mythology' },
    { text: 'Imp', category: 'Mythology' },
    { text: 'Troll', category: 'Mythology' },
    { text: 'Ogre', category: 'Mythology' },
    { text: 'Nymph', category: 'Mythology' },
    { text: 'Giant', category: 'Mythology' },
    { text: 'Elf', category: 'Mythology' },

    { text: 'angelina jolie', category: 'Famous person' },
    { text: 'bob dylan', category: 'Famous person' },
    { text: 'brad pitt', category: 'Famous person' },
    { text: 'bruce lee', category: 'Famous person' },
    { text: 'geronimo', category: 'Famous person' },
    { text: 'greenday', category: 'Famous person' },
    { text: 'kate moss', category: 'Famous person' },
    { text: 'lady gaga', category: 'Famous person' },
    { text: 'lil wayne', category: 'Famous person' },
    { text: 'ludacris', category: 'Famous person' },
    { text: 'mc hammer', category: 'Famous person' },
    { text: 'tom hanks', category: 'Famous person' },
    { text: 'beckham', category: 'Famous person' },
    { text: 'colbert', category: 'Famous person' },
    { text: 'jay leno', category: 'Famous person' },
    { text: 'lincoln', category: 'Famous person' },
    { text: 'picasso', category: 'Famous person' },
    { text: 'rihanna', category: 'Famous person' },
    { text: 'van gogh', category: 'Famous person' },
    { text: 'justin bieber', category: 'Famous person' },
    { text: 'eminem', category: 'Famous person' },
    { text: 'gandhi', category: 'Famous person' },
    { text: 'madonna', category: 'Famous person' },
    { text: 'pitbull', category: 'Famous person' },
	{ text: 'vincent van gogh', category: 'Famous person' },
	{ text: 'Donald Trump', category: 'Famous person' },

    { text: 'archery', category: 'Sports' },
    { text: 'baseball', category: 'Sports' },
    { text: 'Basketball', category: 'Sports' },
    { text: 'bowling', category: 'Sports' },
    { text: 'Boxing', category: 'Sports' },
    { text: 'Curling', category: 'Sports' },
	{ text: 'Cricket', category: 'Sports' },
    { text: 'dumbbell', category: 'Sports' },
    { text: 'fencing', category: 'Sports' },
    { text: 'fishing', category: 'Sports' },
    { text: 'football', category: 'Sports' },
    { text: 'frisbee', category: 'Sports' },
    { text: 'goal post', category: 'Sports' },
    { text: 'Golf', category: 'Sports' },
    { text: 'half pipe', category: 'Sports' },
    { text: 'handball', category: 'Sports' },
    { text: 'homerun', category: 'Sports' },
    { text: 'iceskate', category: 'Sports' },
    { text: 'javelin', category: 'Sports' },
    { text: 'jumprope', category: 'Sports' },
    { text: 'Lacrosse', category: 'Sports' },
    { text: 'longjump', category: 'Sports' },
    { text: 'minigolf', category: 'Sports' },
    { text: 'Netball', category: 'Sports' },
    { text: 'olympics', category: 'Sports' },
    { text: 'pingpong', category: 'Sports' },
    { text: 'rebound', category: 'Sports' },
    { text: 'referee', category: 'Sports' },
	{ text: 'Rock climbing', category: 'Sports' },
    { text: 'slamdunk', category: 'Sports' },
    { text: 'sledding', category: 'Sports' },
	{ text: 'soccer', category: 'Sports' },
    { text: 'Surfing', category: 'Sports' },
	{ text: 'swimming', category: 'Sports' },
	{ text: 'Tennis', category: 'Sports' },
    { text: 'Volleyball', category: 'Sports' },


    { text: 'Autobots', category: 'Pop Culture' },
    { text: 'Catwoman', category: 'Pop Culture' },
    { text: 'Garfield', category: 'Pop Culture' },
    { text: 'iron chef', category: 'Pop Culture' },
    { text: 'splinter', category: 'Pop Culture' },
    { text: 'superman', category: 'Pop Culture' },
    { text: 'aladdin', category: 'Pop Culture' },
    { text: 'aquaman', category: 'Pop Culture' },
    { text: 'asterix', category: 'Pop Culture' },
    { text: 'hawkeye', category: 'Pop Culture' },
    { text: 'metroid', category: 'Pop Culture' },
    { text: 'Pikachu', category: 'Pop Culture' },
    { text: 'riddler', category: 'Pop Culture' },
    { text: 'rugrats', category: 'Pop Culture' },
    { text: 'Twoface', category: 'Pop Culture' },
    { text: 'avatar', category: 'Pop Culture' },
    { text: 'barbie', category: 'Pop Culture' },
    { text: 'batman', category: 'Pop Culture' },
    { text: 'beavis', category: 'Pop Culture' },
    { text: 'bowser', category: 'Pop Culture' },
    { text: 'Legend of Zelda', category: 'Pop Culture' },
    { text: 'Mickey Mouse', category: 'Pop Culture' },
    { text: 'Voldemort', category: 'Pop Culture' },
    { text: 'Conan the Barbarian', category: 'Pop Culture' },
    { text: 'The Simpsons', category: 'Pop Culture' },
    { text: 'Rick & Morty', category: 'Pop Culture' },
    { text: 'Kermit', category: 'Pop Culture' },
    { text: 'Spongebob', category: 'Pop Culture' },
    { text: 'Simba', category: 'Pop Culture' },
	{ text: 'Scooby Doo', category: 'Pop Culture' },

    { text: 'Artist', category: 'Profession' },
    { text: 'Assassin', category: 'Profession' },
    { text: 'Barber', category: 'Profession' },
    { text: 'Butcher', category: 'Profession' },
    { text: 'Captain', category: 'Profession' },
    { text: 'Cashier', category: 'Profession' },
	{ text: 'Chef', category: 'Profession' },
	{ text: 'Clown', category: 'Profession' },
	{ text: 'Cook', category: 'Profession' },
    { text: 'Cowboy', category: 'Profession' },
    { text: 'Cowgirl', category: 'Profession' },
    { text: 'Dentist', category: 'Profession' },
    { text: 'DJ', category: 'Profession' },
    { text: 'Doctor', category: 'Profession' },
    { text: 'Drummer', category: 'Profession' },
    { text: 'Farmer', category: 'Profession' },
    { text: 'Firefighter', category: 'Profession' },
	{ text: 'Hacker', category: 'Profession' },
    { text: 'Gangster', category: 'Profession' },
    { text: 'Gardener', category: 'Profession' },
    { text: 'Gymnast', category: 'Profession' },
    { text: 'Janitor', category: 'Profession' },
	{ text: 'Lawyer', category: 'Profession' },
    { text: 'Magician', category: 'Profession' },
    { text: 'Mailman', category: 'Profession' },
    { text: 'Milkman', category: 'Profession' },
    { text: 'Movie Director', category: 'Profession' },
    { text: 'Opera Singer', category: 'Profession' },
    { text: 'Painter', category: 'Profession' },
	{ text: 'Pilot', category: 'Profession' },
    { text: 'Plumber', category: 'Profession' },
    { text: 'Policeman', category: 'Profession' },
    { text: 'Poolboy', category: 'Profession' },
    { text: 'Priest', category: 'Profession' },
    { text: 'Princess', category: 'Profession' },
    { text: 'Sheriff', category: 'Profession' },
    { text: 'Soldier', category: 'Profession' },
    { text: 'Surgeon', category: 'Profession' },
    { text: 'Teacher', category: 'Profession' },
    { text: 'Teacher', category: 'Profession' },
    { text: 'Waiter', category: 'Profession' },
    { text: 'Warrior', category: 'Profession' },
    { text: 'Window cleaner ', category: 'Profession' },
    { text: 'Wrestler', category: 'Profession' },

    { category: 'Animal', text: 'aardvark' },
    { category: 'Animal', text: 'Alpaca' },
    { category: 'Animal', text: 'ant' },
    { category: 'Animal', text: 'anteater' },
    { category: 'Animal', text: 'armadillo' },
    { category: 'Animal', text: 'baboon' },
    { category: 'Animal', text: 'badger' },
	{ category: 'Animal', text: 'bat' },
    { category: 'Animal', text: 'bear' },
    { category: 'Animal', text: 'beaver' },
    { category: 'Animal', text: 'bee' },
    { category: 'Animal', text: 'bird' },
    { category: 'Animal', text: 'buffalo' },
    { category: 'Animal', text: 'bull' },
    { category: 'Animal', text: 'calf' },
    { category: 'Animal', text: 'camel' },
    { category: 'Animal', text: 'cat' },
    { category: 'Animal', text: 'Caterpillar' },
	{ category: 'Animal', text: 'catfish' },
	{ category: 'Animal', text: 'Chameleon' },
    { category: 'Animal', text: 'cheetah' },
    { category: 'Animal', text: 'chicken' },
    { category: 'Animal', text: 'chimpanzee' },
    { category: 'Animal', text: 'Chihuahua ' },
    { category: 'Animal', text: 'Cicada ' },
	{ category: 'Animal', text: 'cockroach' },
    { category: 'Animal', text: 'cow' },
    { category: 'Animal', text: 'crane' },
	{ category: 'Animal', text: 'crab' },
    { category: 'Animal', text: 'Cricket' },
    { category: 'Animal', text: 'crocodile' },
    { category: 'Animal', text: 'deer' },
    { category: 'Animal', text: 'dinosaur' },
    { category: 'Animal', text: 'dog' },
    { category: 'Animal', text: 'dolphin' },
    { category: 'Animal', text: 'donkey' },
    { category: 'Animal', text: 'duck' },
	{ category: 'Animal', text: 'dragonfly' },
    { category: 'Animal', text: 'eagle' },
    { category: 'Animal', text: 'elephant' },
	{ category: 'Animal', text: 'firefly' },
    { category: 'Animal', text: 'fish' },
    { category: 'Animal', text: 'flamingo' },
    { category: 'Animal', text: 'fly' },
    { category: 'Animal', text: 'fox' },
    { category: 'Animal', text: 'Frog' },
    { category: 'Animal', text: 'Giraffe' },
    { category: 'Animal', text: 'goat' },
    { category: 'Animal', text: 'goldfish' },
	{ category: 'Animal', text: 'Goose' },
    { category: 'Animal', text: 'gorilla' },
    { category: 'Animal', text: 'Grasshopper' },
    { category: 'Animal', text: 'hamster' },
    { category: 'Animal', text: 'hippopotamus' },
    { category: 'Animal', text: 'horse' },
    { category: 'Animal', text: 'hyena' },
    { category: 'Animal', text: 'jaguar' },
    { category: 'Animal', text: 'kangaroo' },
    { category: 'Animal', text: 'kitten' },
    { category: 'Animal', text: 'ladybug' },
    { category: 'Animal', text: 'leopard' },
    { category: 'Animal', text: 'lion' },
    { category: 'Animal', text: 'lizard' },
    { category: 'Animal', text: 'llama' },
    { category: 'Animal', text: 'lobster' },
    { category: 'Animal', text: 'mammoth' },
    { category: 'Animal', text: 'monkey' },
    { category: 'Animal', text: 'mosquito' },
	{ category: 'Animal', text: 'moose' },
    { category: 'Animal', text: 'Mouse' },
    { category: 'Animal', text: 'narwhal' },
    { category: 'Animal', text: 'octopus' },
    { category: 'Animal', text: 'ostrich' },
    { category: 'Animal', text: 'otter' },
    { category: 'Animal', text: 'owl' },
    { category: 'Animal', text: 'oyster' },
    { category: 'Animal', text: 'panda' },
    { category: 'Animal', text: 'Pangolin' },
	{ category: 'Animal', text: 'parrot' },
    { category: 'Animal', text: 'panther' },
    { category: 'Animal', text: 'peacock' },
    { category: 'Animal', text: 'pelican' },
    { category: 'Animal', text: 'penguin' },
    { category: 'Animal', text: 'pig' },
    { category: 'Animal', text: 'pigeon' },
	{ category: 'Animal', text: 'pitbull' },
	{ category: 'Animal', text: 'Platypus' },
    { category: 'Animal', text: 'porcupine' },
	{ category: 'Animal', text: 'Poodle' },
    { category: 'Animal', text: 'puppy' },
    { category: 'Animal', text: 'rabbit' },
    { category: 'Animal', text: 'raccoon' },
    { category: 'Animal', text: 'rat' },
    { category: 'Animal', text: 'reindeer' },
	{ category: 'Animal', text: 'reptile' },
    { category: 'Animal', text: 'rhinoceros' },
    { category: 'Animal', text: 'rooster' },
    { category: 'Animal', text: 'scorpion' },
    { category: 'Animal', text: 'seagull' },
    { category: 'Animal', text: 'seahorse' },
    { category: 'Animal', text: 'Seal' },
    { category: 'Animal', text: 'shark' },
    { category: 'Animal', text: 'sheep' },
    { category: 'Animal', text: 'shrimp' },
	{ category: 'Animal', text: 'Skunk' },
    { category: 'Animal', text: 'snail' },
    { category: 'Animal', text: 'snake' },
    { category: 'Animal', text: 'spider' },
    { category: 'Animal', text: 'squid' },
    { category: 'Animal', text: 'squirrel' },
    { category: 'Animal', text: 'starfish' },
    { category: 'Animal', text: 'stork' },
    { category: 'Animal', text: 'swan' },
    { category: 'Animal', text: 'tadpole' },
    { category: 'Animal', text: 'tiger' },
    { category: 'Animal', text: 'toad' },
    { category: 'Animal', text: 'tropical fish' },
    { category: 'Animal', text: 'tuna' },
    { category: 'Animal', text: 'turkey' },
    { category: 'Animal', text: 'turtle' },
    { category: 'Animal', text: 'tortoise' },
	{ category: 'Animal', text: 'vulture' },
	{ category: 'Animal', text: 'walrus' },
    { category: 'Animal', text: 'whale' },
    { category: 'Animal', text: 'wolf' },
    { category: 'Animal', text: 'Wombat' },
    { category: 'Animal', text: 'Worm' },
	{ category: 'Animal', text: 'zebra' },

    { text: 'Bacon', category: 'Food' },
    { text: 'Baguette', category: 'Food' },
    { text: 'Barbeque', category: 'Food' },
    { text: 'Beans', category: 'Food' },
    { text: 'Beer', category: 'Food' },
    { text: 'Burrito', category: 'Food' },
	{ text: 'Cake', category: 'Food' },
    { text: 'Cereal', category: 'Food' },
    { text: 'Champagne', category: 'Food' },
    { text: 'Cheese', category: 'Food' },
    { text: 'Chicken Wings', category: 'Food' },
    { text: 'Coffee', category: 'Food' },
    { text: 'Corndog', category: 'Food' },
	{ text: 'Croissant', category: 'Food' },
    { text: 'Cupcake', category: 'Food' },
    { text: 'Eggroll', category: 'Food' },
    { text: 'Espresso', category: 'Food' },
    { text: 'Fast Food', category: 'Food' },
    { text: 'Fish and Chips', category: 'Food' },
    { text: 'Frosting', category: 'Food' },
	{ text: 'Hamburger', category: 'Food' },
    { text: 'Hambone', category: 'Food' },
    { text: 'Hamwich', category: 'Food' },
    { text: 'Hot sauce', category: 'Food' },
    { text: 'Junk Food', category: 'Food' },
    { text: 'Kebab', category: 'Food' },
	{ text: 'Ketchup', category: 'Food' },
	{ text: 'Lasagna', category: 'Food' },
    { text: 'Lemonade', category: 'Food' },
    { text: 'Macaroni', category: 'Food' },
    { text: 'Martini', category: 'Food' },
    { text: 'Mashed Potatoes', category: 'Food' },
    { text: 'Meatballs', category: 'Food' },
	{ text: 'Milk', category: 'Food' },
    { text: 'Mushroom', category: 'Food' },
    { text: 'Mustard', category: 'Food' },
    { text: 'Noodles', category: 'Food' },
    { text: 'Oatmeal', category: 'Food' },
    { text: 'Pancake', category: 'Food' },
    { text: 'Pasta', category: 'Food' },
    { text: 'Pie', category: 'Food' },
    { text: 'Pizza', category: 'Food' },
    { text: 'Popcorn', category: 'Food' },
    { text: 'Pretzel', category: 'Food' },
    { text: 'Pumpkin', category: 'Food' },
    { text: 'Salad', category: 'Food' },
    { text: 'Sandwich', category: 'Food' },
    { text: 'Sausage', category: 'Food' },
    { text: 'SeaFood', category: 'Food' },
    { text: 'Smoothie', category: 'Food' },
    { text: 'Snowcone', category: 'Food' },
    { text: 'Soy Sauce', category: 'Food' },
    { text: 'Sushi', category: 'Food' },
    { text: 'Tea', category: 'Food' },
    { text: 'Tequila', category: 'Food' },
	{ text: 'Waffles', category: 'Food' },
    { text: 'Whiskey', category: 'Food' },


    { text: 'Horror', category: 'Film Genres' },
    { text: 'Action', category: 'Film Genres' },
    { text: 'Thriller', category: 'Film Genres' },
    { text: 'Sci-Fi', category: 'Film Genres' },
    { text: 'Rom-Com', category: 'Film Genres' },
    { text: 'Western', category: 'Film Genres' },
    { text: 'Comedy', category: 'Film Genres' },
    { text: 'Gangster', category: 'Film Genres' },
    { text: 'Slapstick', category: 'Film Genres' },
    { text: 'War', category: 'Film Genres' },
    { text: 'Documentry', category: 'Film Genres' },
    { text: 'Mockumentry', category: 'Film Genres' },
    { text: 'Musical', category: 'Film Genres' },
    { text: 'Animation', category: 'Film Genres' },
    { text: 'Disasters', category: 'Film Genres' },
    { text: 'Zombies', category: 'Film Genres' },
    { text: 'Sport', category: 'Film Genres' },

    { text: 'A Clockwork Orange', category: 'Movies' },
	{ text: 'Armagedon', category: 'Movies' },
    { text: 'Alien', category: 'Movies' },
    { text: 'Austin Powers', category: 'Movies' },
    { text: 'Avengers', category: 'Movies' },
    { text: 'Back to the Future', category: 'Movies' },
    { text: 'Braveheart', category: 'Movies' },
	{ text: 'Beetlejuice', category: 'Movies' },
    { text: 'Die Hard', category: 'Movies' },
    { text: 'E.T.', category: 'Movies' },
    { text: 'Fargo', category: 'Movies' },
    { text: 'Finding Nemo', category: 'Movies' },
    { text: 'Forrest Gump', category: 'Movies' },
	{ text: 'Frozen', category: 'Movies' },
    { text: 'Gladiator', category: 'Movies' },
    { text: 'Golden Eye', category: 'Movies' },
    { text: 'Gone with The Wind', category: 'Movies' },
    { text: 'Groundhog Day', category: 'Movies' },
    { text: 'Home Alone', category: 'Movies' },
    { text: 'Inception', category: 'Movies' },
    { text: 'Indiana Jones', category: 'Movies' },
    { text: 'Inglourious Basterds', category: 'Movies' },
    { text: 'Jaws', category: 'Movies' },
    { text: 'Jurassic Park', category: 'Movies' },
    { text: 'King Kong', category: 'Movies' },
    { text: 'Lion King', category: 'Movies' },
    { text: 'Mary Poppins', category: 'Movies' },
    { text: 'Minority Report', category: 'Movies' },
    { text: 'Mission Impossible', category: 'Movies' },
    { text: 'Monty Python and the Holy Grail', category: 'Movies' },
    { text: 'Princess Bride', category: 'Movies' },
    { text: 'Pulp Fiction', category: 'Movies' },
    { text: 'Rocky Horror Picture Show', category: 'Movies' },
    { text: 'Rocky', category: 'Movies' },
    { text: 'Saving Private Ryan', category: 'Movies' },
    { text: 'Scarface', category: 'Movies' },
    { text: 'Shrek', category: 'Movies' },
    { text: 'Star Wars', category: 'Movies' },
    { text: 'Terminator', category: 'Movies' },
    { text: 'The Good, the Bad and the Ugly', category: 'Movies' },
    { text: 'The Green Mile', category: 'Movies' },
    { text: 'The Lord Of the Rings', category: 'Movies' },
    { text: 'The Matrix', category: 'Movies' },
    { text: 'The Shawshank Redemption', category: 'Movies' },
    { text: 'The Social Network', category: 'Movies' },
    { text: 'The Wizard of Oz', category: 'Movies' },
    { text: 'Titanic', category: 'Movies' },
    { text: 'Toy Story', category: 'Movies' },
    { text: 'West Side Story', category: 'Movies' },
    { text: 'Wonder Woman', category: 'Movies' },
    { text: 'X-Men', category: 'Movies' },
	{ text: 'Robocop', category: 'Movies' },


    { text: 'Sour Candy', category: 'Snacks' },
    { text: 'Twinkie', category: 'Snacks' },
    { text: 'Lollipop', category: 'Snacks' },
    { text: 'Popsicle', category: 'Snacks' },
    { text: 'Skittles', category: 'Snacks' },
    { text: 'Brownie', category: 'Snacks' },
    { text: 'Cookie', category: 'Snacks' },
    { text: 'Doritos', category: 'Snacks' },
    { text: 'Sour Candy', category: 'Snacks' },
    { text: 'Icecream', category: 'Snacks' },

    { text: 'The Pyramids', category: 'Famous Landmark' },
    { text: 'Christ the Redeemer statue', category: 'Famous Landmark' },
    { text: 'The Great Chinese Wall', category: 'Famous Landmark' },
    { text: 'Leaning Tower of Pisa', category: 'Famous Landmark' },
    { text: 'Empire State Building', category: 'Famous Landmark' },
    { text: 'Colosseum', category: 'Famous Landmark' },
    { text: 'The Eiffel Tower', category: 'Famous Landmark' },
    { text: 'Statue of Liberty', category: 'Famous Landmark' },
    { text: 'The Sphinx', category: 'Famous Landmark' },
    { text: 'The Little Mermaid', category: 'Famous Landmark' },
    { text: 'The Taj Mahal', category: 'Famous Landmark' },
    { text: 'Big Ben', category: 'Famous Landmark' },
    { text: 'Loch Ness', category: 'Famous Landmark' },
    { text: 'Brandenburg Gate', category: 'Famous Landmark' },
    { text: 'Acropolis', category: 'Famous Landmark' },
    { text: 'Stonehenge', category: 'Famous Landmark' },
    { text: 'Easter Island', category: 'Famous Landmark' },
    { text: 'Capitol Hill', category: 'Famous Landmark' },
    { text: 'Niagra Falls', category: 'Famous Landmark' },
    { text: 'Mount Rushmore', category: 'Famous Landmark' },
    { text: 'Grand Canyon', category: 'Famous Landmark' },
    { text: 'Fontana de Trevi', category: 'Famous Landmark' },
    { text: 'Sydney Opera House', category: 'Famous Landmark' },
    { text: 'Golden Gate Bridge ', category: 'Famous Landmark' },
    { text: 'The Forbidden City', category: 'Famous Landmark' },
    { text: 'The Kremlin', category: 'Famous Landmark' },
    { text: 'The Louvre ', category: 'Famous Landmark' },
    { text: 'The Hollywood Sign ', category: 'Famous Landmark' },

    { text: 'Cinderella', category: 'Fairytale' },
    { text: 'The Three Little Pigs', category: 'Fairytale' },
    { text: 'The Ugly Duckling', category: 'Fairytale' },
    { text: 'The Tin Soldier', category: 'Fairytale' },
    { text: 'The Tinderbox', category: 'Fairytale' },
    { text: 'The Princess and the Pea', category: 'Fairytale' },
    { text: 'Thumbelina', category: 'Fairytale' },
    { text: 'The Little Mermaid', category: 'Fairytale' },
    { text: 'Thumbelina', category: 'Fairytale' },
    { text: 'The Steadfast Tin Soldier', category: 'Fairytale' },
    { text: "The Emperor's New Clothes", category: 'Fairytale' },
    { text: 'Goldilocks and the Three Bears', category: 'Fairytale' },
    { text: 'Thumbelina', category: 'Fairytale' },
    { text: 'Sleeping Beauty', category: 'Fairytale' },
    { text: 'Snow White', category: 'Fairytale' },
    { text: 'Rapunzel', category: 'Fairytale' },
    { text: 'The Frog Prince', category: 'Fairytale' },
    { text: 'Hansel and Gretel', category: 'Fairytale' },
    { text: 'The Golden Fish', category: 'Fairytale' },
    { text: 'Rumpelstiltskin', category: 'Fairytale' },
    { text: 'The Golden Goose', category: 'Fairytale' },
    { text: 'Puss in Boots', category: 'Fairytale' },
    { text: 'Aladdin', category: 'Fairytale' },
    { text: 'Beauty and the Beast', category: 'Fairytale' },
    { text: 'Ali Baba and the Forty Thieves', category: 'Fairytale' },
    { text: 'Sinbad', category: 'Fairytale' },
    { text: 'The Fisherman and the Jinni', category: 'Fairytale' },

];

words.de = [
    { text: 'Oma', category: 'Familie' },
    { text: 'opa', category: 'Familie' },
    { text: 'Ehemann', category: 'Familie' },
    { text: 'Eltern', category: 'Familie' },
    { text: 'Ehefrau', category: 'Familie' },
    { text: 'Onkel', category: 'Familie' },
    { text: 'Tante', category: 'Familie' },
    { text: 'Vater', category: 'Familie' },
    { text: 'Mutter', category: 'Familie' },
    { text: 'Stiefschwester', category: 'Familie' },
    { text: 'Stiefbruder', category: 'Familie' },
    { text: 'Stiefvater', category: 'Familie' },
    { text: 'Stiefmutter', category: 'Familie' },
    { text: 'Patenonkel', category: 'Familie' },
    { text: 'Patentante', category: 'Familie' },
    { text: 'Schwiegermutter', category: 'Familie' },
    { text: 'Schwiegervater', category: 'Familie' },
    { text: 'Kinder', category: 'Familie' },
    { text: 'Bruder', category: 'Familie' },
    { text: 'Schwester', category: 'Familie' },
    { text: 'Cousin', category: 'Familie' },
    { text: 'Großmutter', category: 'Familie' },
    { text: 'Enkel', category: 'Familie' },
    { text: 'Nichte', category: 'Familie' },
    { text: 'Neffe', category: 'Familie' },

	{ text: 'Neujahr', category: 'Festlichkeit' },
    { text: 'Hochzeit', category: 'Festlichkeit' },
    { text: 'Geburtstag', category: 'Festlichkeit' },
    { text: 'Halloween', category: 'Festlichkeit' },
    { text: 'oktoberfest', category: 'Festlichkeit' },
    { text: 'weihnachten', category: 'Festlichkeit' },
    { text: 'Silvester', category: 'Festlichkeit' },
    { text: 'Murmeltiertag', category: 'Festlichkeit' },
    { text: 'Valentine`s Day', category: 'Festlichkeit' },
    { text: 'St. Patrick`s Day', category: 'Festlichkeit' },
    { text: 'Pfingsten', category: 'Festlichkeit' },
    { text: 'Ostern', category: 'Festlichkeit' },
    { text: 'Ramadan', category: 'Festlichkeit' },
    { text: 'Muttertag', category: 'Festlichkeit' },
    { text: 'Independence Day', category: 'Festlichkeit' },
    { text: 'Black Friday', category: 'Festlichkeit' },
    { text: 'Thanksgiving', category: 'Festlichkeit' },
    { text: 'Bundestagswahl', category: 'Festlichkeit' },
    { text: 'Abschlussfeier', category: 'Festlichkeit' },


    { text: 'Stuhl', category: 'Möbel' },
    { text: 'Barhocker', category: 'Möbel' },
    { text: 'Bücherregal', category: 'Möbel' },
    { text: 'Wasserbett', category: 'Möbel' },
    { text: 'badewanne', category: 'Möbel' },
    { text: 'Etagenbett', category: 'Möbel' },
    { text: 'Schrank', category: 'Möbel' },
    { text: 'Kommode', category: 'Möbel' },
    { text: 'Bett', category: 'Möbel' },

    { text: 'Kettensäge', category: 'Werkzeug' },
    { text: 'Schere', category: 'Werkzeug' },
    { text: 'Pinzette', category: 'Werkzeug' },
    { text: 'Zirkel', category: 'Werkzeug' },
    { text: 'Brechstange', category: 'Werkzeug' },
    { text: 'Kehrschaufel', category: 'Werkzeug' },
    { text: 'Hefter', category: 'Werkzeug' },

    { text: 'Lippenstift', category: 'Toilettenartikel' },
    { text: 'Parfüm', category: 'Toilettenartikel' },
    { text: 'Shampoo', category: 'Toilettenartikel' },
    { text: 'Nagelfeile', category: 'Toilettenartikel' },
    { text: 'Sonnencreme', category: 'Toilettenartikel' },
    { text: 'Haarfärbemittel', category: 'Toilettenartikel' },
    { text: 'Haargel', category: 'Toilettenartikel' },
    { text: 'Wimperntusche', category: 'Toilettenartikel' },

    { text: 'Computer', category: 'Computing' },
    { text: 'facebook', category: 'Computing' },
    { text: 'firewall', category: 'Computing' },
    { text: 'Tastatur', category: 'Computing' },
    { text: 'Passwort', category: 'Computing' },
    { text: 'hashtag', category: 'Computing' },
    { text: 'macbook', category: 'Computing' },
    { text: 'twitter', category: 'Computing' },
	{ text: 'reddit', category: 'Computing' },
	{ text: 'snapchat', category: 'Computing' },
	{ text: 'instagram', category: 'Computing' },


	{ category: 'Waffe', text: 'Kriegsaxt' },
	{ category: 'Waffe', text: 'Bayonett' },
	{ category: 'Waffe', text: 'Panzerfaust' },
	{ category: 'Waffe', text: 'Kanone' },
	{ category: 'Waffe', text: 'Katapult' },
	{ category: 'Waffe', text: 'Armbrust' },
	{ category: 'Waffe', text: 'Dynamit' },
	{ category: 'Waffe', text: 'Pistole' },
	{ category: 'Waffe', text: 'Rakete' },
	{ category: 'Waffe', text: 'Shotgun' },
	{ category: 'Waffe', text: 'Schwert' },
	{ category: 'Waffe', text: 'Kitana' },
	{ category: 'Waffe', text: 'Torpedo' },
	{ category: 'Waffe', text: 'Warhammer'},

    { text: 'Augenklappe', category: 'Accessoires' },
    { text: 'Stirnband', category: 'Accessoires' },
    { text: 'Knieschoner', category: 'Accessoires' },
    { text: 'Halskette', category: 'Accessoires' },
    { text: 'nosering', category: 'Accessoires' },
    { text: 'partyhat', category: 'Accessoires' },
    { text: 'Schnürsenkel', category: 'Accessoires' },
    { text: 'Regenschirm', category: 'Accessoires' },
    { text: 'Halstuch', category: 'Accessoires' },
    { text: 'ohrring', category: 'Accessoires' },
    { text: 'Haargummi', category: 'Accessoires' },
    { text: 'Handtasche', category: 'Accessoires' },
	{ category: 'Accessoires', text: 'Taschentuch' },

    { category: 'Kleidung', text: 'Keuschheitsgürtel' },
    { category: 'Kleidung', text: 'Tophat' },
    { category: 'Kleidung', text: 'Hosenanzug' },
    { category: 'Kleidung', text: 'Halstuch' },
    { category: 'Kleidung', text: 'Gürtel' },
    { category: 'Kleidung', text: 'Bikini' },
    { category: 'Kleidung', text: 'Stiefel' },
    { category: 'Kleidung', text: 'Fliege' },
	{ category: 'Kleidung', text: 'Tophat' },
	{ category: 'Kleidung', text: 'Cowboyhut' },
    { category: 'Kleidung', text: 'Mütze' },
    { category: 'Kleidung', text: 'Mantel' },
    { category: 'Kleidung', text: 'Kleid' },
    { category: 'Kleidung', text: 'Ohrenschützer' },
    { category: 'Kleidung', text: 'Augenklappe' },
    { category: 'Kleidung', text: 'Brille' },
    { category: 'Kleidung', text: 'Handschuhe' },
    { category: 'Kleidung', text: 'Haargummi' },
	{ category: 'Kleidung', text: 'Hoodie' },
    { category: 'Kleidung', text: 'Hut' },
    { category: 'Kleidung', text: 'Stirnband' },
    { category: 'Kleidung', text: 'Jacke' },
    { category: 'Kleidung', text: 'Jeans' },
    { category: 'Kleidung', text: 'Knieschoner' },
    { category: 'Kleidung', text: 'Fäustlinge' },
    { category: 'Kleidung', text: 'Halskette' },
    { category: 'Kleidung', text: 'Latzhose' },
    { category: 'Kleidung', text: 'Pyjama' },
    { category: 'Kleidung', text: 'Partyhut' },
    { category: 'Kleidung', text: 'Regenmantel' },
    { category: 'Kleidung', text: 'Sandalen' },
    { category: 'Kleidung', text: 'Schal' },
    { category: 'Kleidung', text: 'Hemd' },
    { category: 'Kleidung', text: 'Schuhe' },
    { category: 'Kleidung', text: 'Rock' },
    { category: 'Kleidung', text: 'Hausschuhe' },
    { category: 'Kleidung', text: 'Turnschuhe' },
    { category: 'Kleidung', text: 'Socken' },
    { category: 'Kleidung', text: 'Sombrero' },
    { category: 'Kleidung', text: 'Strümpfe' },
    { category: 'Kleidung', text: 'Anzug' },
    { category: 'Kleidung', text: 'Pullover' },
    { category: 'Kleidung', text: 'Sweatshirt' },
    { category: 'Kleidung', text: 'Schwimmanzug' },
    { category: 'Kleidung', text: 't-shirt' },
    { category: 'Kleidung', text: 'Krawatte' },
    { category: 'Kleidung', text: 'Hose' },
    { category: 'Kleidung', text: 'Unterhosen' },

    { text: 'Krücken', category: 'Medizin' },
    { text: 'Schuppen', category: 'Medizin' },
    { text: 'Zahnersatz', category: 'Medizin' },
    { text: 'Erste Hilfe', category: 'Medizin' },
    { text: 'Kopfschmerzen', category: 'Medizin' },
    { text: 'Krankenhaus', category: 'Medizin' },
    { text: 'Schlaflosigkeit', category: 'Medizin' },
    { text: 'Medizin', category: 'Medizin' },
    { text: 'Papierschnitt', category: 'Medizin' },
    { text: 'Seekrankheit', category: 'Medizin' },
    { text: 'Sonnenbrand', category: 'Medizin' },
    { text: 'Impfung', category: 'Medizin' },
    { text: 'Vitamin', category: 'Medizin' },

    { text: 'hongkong', category: 'Geografie' },
    { text: 'schottland', category: 'Geografie' },
    { text: 'amerika', category: 'Geografie' },
    { text: 'atlanta', category: 'Geografie' },
    { text: 'bahamas', category: 'Geografie' },
    { text: 'england', category: 'Geografie' },
    { text: 'finland', category: 'Geografie' },
    { text: 'florida', category: 'Geografie' },
    { text: 'deutschland', category: 'Geografie' },
    { text: 'holland', category: 'Geografie' },
    { text: 'ireland', category: 'Geografie' },
    { text: 'jamaika', category: 'Geografie' },
    { text: 'new-york', category: 'Geografie' },
    { text: 'orlando', category: 'Geografie' },
	{ text: 'Berlin', category: 'Geografie' },
	{ text: 'Stuttgart', category: 'Geografie' },
	{ text: 'Frankreich', category: 'Geografie' },
	{ text: 'Italien', category: 'Geografie' },



    { text: 'kohl', category: 'Pflanze' },
    { text: 'Dattelpflaume', category: 'Pflanze' },
    { text: 'Gurke', category: 'Pflanze' },
    { text: 'Zucchini', category: 'Pflanze' },
    { text: 'Wassermelone', category: 'Pflanze' },
    { text: 'Mango', category: 'Pflanze' },
    { text: 'Zitrone', category: 'Pflanze' },
    { text: 'Limette', category: 'Pflanze' },
    { text: 'Kartoffel', category: 'Pflanze' },
    { text: 'Kaktus', category: 'Pflanze' },
    { text: 'Tomate', category: 'Pflanze' },
    { text: 'Aubergine', category: 'Pflanze' },
    { text: 'Palme', category: 'Pflanze' },
    { text: 'Tannenzapfen', category: 'Pflanze' },
    { text: 'Kiefernbaum', category: 'Pflanze' },
    { text: 'Primrose', category: 'Pflanze' },
    { text: 'Eiche', category: 'Pflanze' },
    { text: 'Seegras', category: 'Pflanze' },
    { text: 'Bambus', category: 'Pflanze' },
    { text: 'Kraut', category: 'Pflanze' },
    { text: 'Persimmon', category: 'Pflanze' },
    { text: 'Gurke', category: 'Pflanze' },
    { text: 'Zucchini', category: 'Pflanze' },
    { text: 'Wassermelone', category: 'Pflanze' },
    { text: 'Mango', category: 'Pflanze' },
    { text: 'Zitrone', category: 'Pflanze' },
    { text: 'Limette', category: 'Pflanze' },
    { text: 'Kartoffel', category: 'Pflanze' },
    { text: 'Kaktus', category: 'Pflanze' },
    { text: 'Tomate', category: 'Pflanze' },
    { text: 'Aubergine', category: 'Pflanze' },
    { text: 'Palme', category: 'Pflanze' },
    { text: 'Tannenzapfen', category: 'Pflanze' },
    { text: 'Pinienbaum', category: 'Pflanze' },
    { text: 'Primrose', category: 'Pflanze' },
    { text: 'Eiche', category: 'Pflanze' },
    { text: 'Seegras', category: 'Pflanze' },
    { text: 'Bamboo', category: 'Pflanze' },
    { text: 'Karotte', category: 'Pflanze' },
    { text: 'Sellerie', category: 'Pflanze' },
    { text: 'Kirsche', category: 'Pflanze' },
    { text: 'Knoblauch', category: 'Pflanze' },
    { text: 'Trauben', category: 'Pflanze' },
    { text: 'Koriander', category: 'Pflanze' },
    { text: 'Banane', category: 'Pflanze' },
    { text: 'Brokkoli', category: 'Pflanze' },
    { text: 'Avocado', category: 'Pflanze' },
    { text: 'Kokosnuss', category: 'Pflanze' },
    { text: 'Pfirsiche', category: 'Pflanze' },
    { text: 'Spinat', category: 'Pflanze' },
    { text: 'Ananas', category: 'Pflanze' },
    { text: 'Weizen', category: 'Pflanze' },
    { text: 'Orange', category: 'Pflanze' },

    { text: 'Wirbelsäule', category: 'Anatomie' },
    { text: 'Stirn', category: 'Anatomie' },
    { text: 'Schnurrbart', category: 'Anatomie' },
    { text: 'Nasenhaar', category: 'Anatomie' },
    { text: 'Schulter', category: 'Anatomie' },
    { text: 'Skelett', category: 'Anatomie' },
    { text: 'Tentakel', category: 'Anatomie' },
    { text: 'Schnurrhaare', category: 'Anatomie' },
    { text: 'Augapfel', category: 'Anatomie' },
    { text: 'Augenbraue', category: 'Anatomie' },
    { text: 'Wimper', category: 'Anatomie' },
    { text: 'Kniescheibe', category: 'Anatomie' },
    { text: 'knuckle', category: 'Anatomie' },
    { text: 'Bauch', category: 'Anatomie' },
    { text: 'unibrow', category: 'Anatomie' },

    { category: 'Ort', text: 'Flughafen' },
    { category: 'Ort', text: 'Mehrfamilienhaus' },
    { category: 'Ort', text: 'Bank' },
    { category: 'Ort', text: 'Friseurladen' },
	{ category: 'Ort', text: 'Bar' },
    { category: 'Ort', text: 'Scheune' },
	{ category: 'Ort', text: 'Strand' },
    { category: 'Ort', text: 'Buchhandlung' },
    { category: 'Ort', text: 'Bowlingbahn' },
    { category: 'Ort', text: 'Bushaltestelle' },
	{ category: 'Ort', text: 'Casino' },
    { category: 'Ort', text: 'Kathedrale' },
	{ category: 'Ort', text: 'Schloss' },
	{ category: 'Ort', text: 'Friedhof' },
	{ category: 'Ort', text: 'Kirche' },
	{ category: 'Ort', text: 'Zirkus' },
    { category: 'Ort', text: 'Convenience Store' },
    { category: 'Ort', text: 'Gerichtsgebäude' },
	{ category: 'Ort', text: 'Wüste' },
    { category: 'Ort', text: 'Kaufhaus' },
    { category: 'Ort', text: 'Disco' },
	{ category: 'Ort', text: 'Dungeon' },
    { category: 'Ort', text: 'Feuerwache' },
	{ category: 'Ort', text: 'Garten' },
    { category: 'Ort', text: 'Tankstelle' },
	{ category: 'Ort', text: 'Golfplatz' },
    { category: 'Ort', text: 'Krankenhaus' },
    { category: 'Ort', text: 'Haus' },
	{ category: 'Ort', text: 'Bibliothek' },
    { category: 'Ort', text: 'Leuchtturm' },
	{ category: 'Ort', text: 'Herrenhaus' },
    { category: 'Ort', text: 'Einkaufszentrum' },
    { category: 'Ort', text: 'Kino' },
    { category: 'Ort', text: 'Museum' },
    { category: 'Ort', text: 'Bürogebäude' },
    { category: 'Ort', text: 'Opernhaus' },
	{ category: 'Ort', text: 'Obstgarten' },
    { category: 'Ort', text: 'Palast' },
	{ category: 'Ort', text: 'Tierhandlung' },
    { category: 'Ort', text: 'Polizeistation' },
    { category: 'Ort', text: 'Postamt' },
	{ category: 'Ort', text: 'Gefängnis' },
	{ category: 'Ort', text: 'Kneipe' },
    { category: 'Ort', text: 'Restaurant' },
	{ category: 'Ort', text: 'Safari' },
    { category: 'Ort', text: 'Sägewerk' },
	{ category: 'Ort', text: 'Schule' },
	{ category: 'Ort', text: 'Wolkenkratzer' },
    { category: 'Ort', text: 'Supermarkt' },
	{ category: 'Ort', text: 'Schwimmbad' },
    { category: 'Ort', text: 'Tempel' },
    { category: 'Ort', text: 'Bahnhof' },
	{ category: 'Ort', text: 'Theater' },
	{ category: 'Ort', text: 'Themenpark' },
	{ category: 'Ort', text: 'Tierklinik' },
	{ category: 'Ort', text: 'Zoo' },

    { text: 'Flugzeug', category: 'Transport' },
    { text: 'Fahrrad', category: 'Transport' },
	{ text: 'Bus', category: 'Transport' },
	{ text: 'Boot', category: 'Transport' },
    { text: 'Hundeschlitten', category: 'Transport' },
	{ text: 'Doppeldecker-Bus', category: 'Transport' },
    { text: 'F-16', category: 'Transport' },
    { text: 'Gabelstapler', category: 'Transport' },
    { text: 'Formel Eins', category: 'Transport' },
    { text: 'Golfwagen', category: 'Transport' },
    { text: 'Hubschrauber', category: 'Transport' },
    { text: 'Hoverboard', category: 'Transport' },
	{ text: 'Eiscreme-Truck', category: 'Transport' },
    { text: 'Jeep', category: 'Transport' },
    { text: 'Minivan', category: 'Transport' },
    { text: 'Ozeandampfer', category: 'Transport' },
    { text: 'Rikscha', category: 'Transport' },
    { text: 'Raketenschiff', category: 'Transport' },
	{ text: 'Ruderboot', category: 'Transport' },
    { text: 'Segelboot', category: 'Transport' },
    { text: 'Scooter', category: 'Transport' },
    { text: 'Shuttle', category: 'Transport' },
	{ text: 'Raumschiff', category: 'Transport' },
	{ text: 'Sportwagen', category: 'Transport' },
    { text: 'Postkutsche', category: 'Transport' },
    { text: 'Dampfschiff', category: 'Transport' },
    { text: 'U-Boot', category: 'Transport' },
    { text: 'Traktor', category: 'Transport' },
    { text: 'Zug', category: 'Transport' },
	{ text: 'Straßenbahn', category: 'Transport' },
    { text: 'Abschleppwagen', category: 'Transport' },
    { text: 'Dreirad', category: 'Transport' },
    { text: 'Schlepper', category: 'Transport' },
    { text: 'Einrad', category: 'Transport' },
    { text: 'Yacht', category: 'Transport' },
    { text: 'Zeppelin', category: 'Transport' },

	{ text: 'AC/DC', category: 'Musikgruppe' },
    { text: 'Adele', category: 'Musikgruppe' },
    { text: 'Beatles', category: 'Musikgruppe' },
    { text: 'Beyonce', category: 'Musikgruppe' },
    { text: 'Billie Eilish', category: 'Musikgruppe' },
    { text: 'Bon Jovi', category: 'Musikgruppe' },
    { text: 'Bruno Mars', category: 'Musikgruppe' },
    { text: 'Childish Gambino', category: 'Musikgruppe' },
    { text: 'Coldplay', category: 'Musikgruppe' },
	{ text: 'David Bowie', category: 'Musikgruppe' },
    { text: 'Daftpunk', category: 'Musikgruppe' },
    { text: 'Dr. Dre', category: 'Musikgruppe' },
    { text: 'Drake', category: 'Musikgruppe' },
    { text: 'Ed Shiran', category: 'Musikgruppe' },
	{ text: 'Elton John', category: 'Musikgruppe' },
    { text: 'Eminem', category: 'Musikgruppe' },
    { text: 'Guns And Roses', category: 'Musikgruppe' },
    { text: 'Jay Z', category: 'Musikgruppe' },
    { text: 'Justin Bieber', category: 'Musikgruppe' },
    { text: 'Justin Timberlake', category: 'Musikgruppe' },
    { text: 'Kanye West', category: 'Musikgruppe' },
    { text: 'Katy Perry', category: 'Musikgruppe' },
    { text: 'Lady Gaga', category: 'Musikgruppe' },
    { text: 'Led Zeppelin', category: 'Musikgruppe' },
    { text: 'Mariah Carey', category: 'Musikgruppe' },
    { text: 'Michael Jackson', category: 'Musikgruppe' },
    { text: 'Muse', category: 'Musikgruppe' },
    { text: 'Nicki Minaj', category: 'Musikgruppe' },
    { text: 'Nirvana', category: 'Musikgruppe' },
    { text: 'Pink Floyd', category: 'Musikgruppe' },
    { text: 'Pitbull', category: 'Musikgruppe' },
    { text: 'Prince', category: 'Musikgruppe' },
    { text: 'Queen', category: 'Musikgruppe' },
    { text: 'Rihana', category: 'Musikgruppe' },
    { text: 'Skrillex', category: 'Musikgruppe' },
    { text: 'Snoop dogg', category: 'Musikgruppe' },
    { text: 'Taylor Swift', category: 'Musikgruppe' },
    { text: 'The Black Eyed Peas', category: 'Musikgruppe' },
    { text: 'Tupac Shakur', category: 'Musikgruppe' },
    { text: 'U2', category: 'Musikgruppe' },
	{ text: 'Die Toten Hosen', category: 'Musikgruppe' },
    { text: 'Die Ärzte', category: 'Musikgruppe' },
    { text: 'Helene Fischer', category: 'Musikgruppe' },
    { text: 'Kettcar', category: 'Musikgruppe' },



    { text: 'Dubstep', category: 'Music Genre' },
    { text: 'House', category: 'Musikgenre' },
    { text: 'Rock', category: 'Musikgenre' },
    { text: 'Hip Hop', category: 'Musikgenre' },
    { text: 'Blues', category: 'Musikgenre' },
    { text: 'Pop', category: 'Musikgenre' },
    { text: 'Jazz', category: 'Musikrichtung' },
    { text: 'Klassisch', category: 'Musikgenre' },
    { text: 'R&B', category: 'Musikgenre' },
    { text: 'Heavy Metal', category: 'Musikgenre' },
    { text: 'Punk', category: 'Musikgenre' },
    { text: 'Country', category: 'Musikgenre' },
    { text: 'Reggae', category: 'Musikgenre' },
    { text: 'Fahrstuhlmusik', category: 'Musikgenre' },
    { text: 'Disco', category: 'Musikgenre' },
    { text: 'Techno', category: 'Musikgenre' },
    { text: 'K-Pop', category: 'Musikgenre' },
    { text: 'Grunge', category: 'Musikgenre' },
    { text: 'Rap', category: 'Musikgenre' },
    { text: 'Swing', category: 'Musikgenre' },

    { text: 'Dudelsack', category: 'Musikinstrument' },
    { text: 'Bassgitarre', category: 'Musikinstrument' },
    { text: 'Jukebox', category: 'Musikinstrument' },
    { text: 'Posaune', category: 'Musikinstrument' },
    { text: 'Schlagzeug', category: 'Musikinstrument' },
    { text: 'Ukulele', category: 'Musikinstrument' },
    { text: 'E-Gitarre', category: 'Musikinstrument' },
    { text: 'Klavier', category: 'Musikinstrument' },
    { text: 'Violine', category: 'Musikinstrument' },
    { text: 'Saxophon', category: 'Musikinstrument' },
    { text: 'Cello', category: 'Musikinstrument' },
    { text: 'Flöte', category: 'Musikinstrument' },
    { text: 'Klarinette', category: 'Musikinstrument' },
    { text: 'Trompete', category: 'Musikinstrument' },
    { text: 'Mundharmonika', category: 'Musikinstrument' },
    { text: 'Harfe', category: 'Musikinstrument' },
    { text: 'Banjo', category: 'Musikinstrument' },
    { text: 'Kastagnetten', category: 'Musikinstrument' },
    { text: 'Kazoo', category: 'Musikinstrument' },
    { text: 'Kuhglocke', category: 'Musikinstrument' },
    { text: 'Cymbal', category: 'Musikinstrument' },
    { text: 'Gong', category: 'Musikinstrument' },
    { text: 'Maraca', category: 'Musikinstrument' },
    { text: 'Marimba', category: 'Musikinstrument' },
    { text: 'Tamburin', category: 'Musikinstrument' },
    { text: 'Triangel', category: 'Musikinstrument' },
    { text: 'Waschbrett', category: 'Musikinstrument' },
    { text: 'Xylophon', category: 'Musikinstrument' },
    { text: 'Akkordeon', category: 'Musikinstrument' },
    { text: 'Horn', category: 'Musikinstrument' },
    { text: 'Signalhorn', category: 'Musikinstrument' },
    { text: 'Didgeridoo', category: 'Musikinstrument' },
    { text: 'Oboe', category: 'Musikinstrument' },
    { text: 'Ocarina', category: 'Musikinstrument' },
    { text: 'Piccolo', category: 'Musikinstrument' },
    { text: 'Pfeife', category: 'Musikinstrument' },
    { text: 'Tuba', category: 'Musikinstrument' },
    { text: 'Sitar', category: 'Musikinstrument' },
    { text: 'Fiddle', category: 'Musikinstrument' },
    { text: 'Laute', category: 'Musikinstrument' },

    { text: 'Genie', category: 'Mythologie' },
    { text: 'Minotaurus', category: 'Mythologie' },
    { text: 'Zauberteppich', category: 'Mythologie' },
    { text: 'Greifen', category: 'Mythologie' },
    { text: 'Minotaurus', category: 'Mythologie' },
    { text: 'Bigfoot', category: 'Mythologie' },
    { text: 'Chimäre', category: 'Mythologie' },
    { text: 'Zyklop', category: 'Mythologie' },
    { text: 'Zentaur', category: 'Mythologie' },
    { text: 'Meerjungfrau', category: 'Mythologie' },
    { text: 'Pegasus', category: 'Mythologie' },
    { text: 'Phönix', category: 'Mythologie' },
    { text: 'Einhorn', category: 'Mythologie' },
    { text: 'Vampir', category: 'Mythologie' },
    { text: 'Drache', category: 'Mythologie' },
    { text: 'Dryade', category: 'Mythologie' },
    { text: 'Geist', category: 'Mythologie' },
    { text: 'Medusa', category: 'Mythologie' },
    { text: 'Mantikor', category: 'Mythologie' },
    { text: 'Satyr', category: 'Mythologie' },
    { text: 'Sphinx', category: 'Mythologie' },
    { text: 'Werwolf', category: 'Mythologie' },
    { text: 'Zombie', category: 'Mythologie' },
    { text: 'Mumie', category: 'Mythologie' },
    { text: 'Golem', category: 'Mythologie' },
    { text: 'Amazonenkriegerin', category: 'Mythologie' },
    { text: 'Echsenmenschen', category: 'Mythologie' },
    { text: 'Basilisk', category: 'Mythologie' },
    { text: 'Goblin', category: 'Mythologie' },
    { text: 'Fee', category: 'Mythologie' },
    { text: 'Ghoul', category: 'Mythologie' },
    { text: 'Kobold', category: 'Mythologie' },
    { text: 'Troll', category: 'Mythologie' },
    { text: 'Oger', category: 'Mythologie' },
    { text: 'Nymphe', category: 'Mythologie' },
    { text: 'Riese', category: 'Mythologie' },
    { text: 'Elf', category: 'Mythologie' },

    { text: 'angelina jolie', category: 'Berühmte Personen' },
    { text: 'bob dylan', category: 'Berühmte Personen' },
    { text: 'brad pitt', category: 'Berühmte Personen' },
    { text: 'bruce lee', category: 'Berühmte Personen' },
    { text: 'geronimo', category: 'Berühmte Personen' },
    { text: 'greenday', category: 'Berühmte Personen' },
    { text: 'kate moss', category: 'Berühmte Personen' },
    { text: 'lady gaga', category: 'Berühmte Personen' },
    { text: 'lil wayne', category: 'Berühmte Personen' },
    { text: 'ludacris', category: 'Berühmte Personen' },
    { text: 'mc hammer', category: 'Berühmte Personen' },
    { text: 'tom hanks', category: 'Berühmte Personen' },
    { text: 'beckham', category: 'Berühmte Personen' },
    { text: 'colbert', category: 'Berühmte Personen' },
    { text: 'jay leno', category: 'Berühmte Personen' },
    { text: 'lincoln', category: 'Berühmte Personen' },
    { text: 'picasso', category: 'Berühmte Personen' },
    { text: 'rihanna', category: 'Berühmte Personen' },
    { text: 'van gogh', category: 'Berühmte Personen' },
    { text: 'justin bieber', category: 'Berühmte Personen' },
    { text: 'eminem', category: 'Berühmte Personen' },
    { text: 'gandhi', category: 'Berühmte Personen' },
    { text: 'madonna', category: 'Berühmte Personen' },
    { text: 'pitbull', category: 'Berühmte Personen' },
	{ text: 'vincent van gogh', category: 'Berühmte Personen' },
	{ text: 'Donald Trump', category: 'Berühmte Personen' },
	{ text: 'Angela Merkel', category: 'Berühmte Personen' },
	{ text: 'Mozart', category: 'Berühmte Personen' },
	{ text: 'Kai Pflaume', category: 'Berühmte Personen' },
	{ text: 'Stefan Raab', category: 'Berühmte Personen' },
	{ text: 'Thomas Gottschalk', category: 'Berühmte Personen' },
	{ text: 'Joko & Klaas', category: 'Berühmte Personen' },

    { text: 'Bogenschießen', category: 'Sport' },
    { text: 'baseball', category: 'Sport' },
    { text: 'Basketball', category: 'Sport' },
    { text: 'Bowling', category: 'Sport' },
    { text: 'Boxen', category: 'Sport' },
    { text: 'Curling', category: 'Sport' },
	{ text: 'Cricket', category: 'Sport' },
    { text: 'Kurzhantel', category: 'Sport' },
    { text: 'Fechten', category: 'Sport' },
    { text: 'Angeln', category: 'Sport' },
    { text: 'Fußball', category: 'Sport' },
    { text: 'frisbee', category: 'Sport' },
    { text: 'Torpfosten', category: 'Sport' },
    { text: 'Golf', category: 'Sport' },
    { text: 'Halfpipe', category: 'Sport' },
    { text: 'handball', category: 'Sport' },
    { text: 'homerun', category: 'Sport' },
    { text: 'Schlittschuhlaufen', category: 'Sports' },
    { text: 'Speerwurf', category: 'Sports' },
    { text: 'Seilspringen', category: 'Sports' },
    { text: 'Lacrosse', category: 'Sports' },
    { text: 'Weitsprung', category: 'Sport' },
    { text: 'Minigolf', category: 'Sport' },
    { text: 'Olympiade', category: 'Sport' },
    { text: 'Tischtennis', category: 'Sport' },
    { text: 'rebound', category: 'Sport' },
    { text: 'schiedsrichter', category: 'Sport' },
	{ text: 'Klettern', category: 'Sport' },
    { text: 'Slamdunk', category: 'Sport' },
    { text: 'Schlittenfahren', category: 'Sport' },
	{ text: 'Fußball', category: 'Sport' },
    { text: 'Surfen', category: 'Sport' },
	{ text: 'Schwimmen', category: 'Sport' },
	{ text: 'Tennis', category: 'Sport' },
    { text: 'Volleyball', category: 'Sport' },

    { text: 'Sandmann', category: 'Popkultur' },
    { text: 'Catwoman', category: 'Popkultur' },
    { text: 'Garfield', category: 'Popkultur' },
    { text: 'superman', category: 'Popkultur' },
    { text: 'aladdin', category: 'Popkultur' },
    { text: 'Ironman', category: 'Popkultur' },
    { text: 'asterix', category: 'Popkultur' },
    { text: 'hawkeye', category: 'Popkultur' },
    { text: 'metroid', category: 'Popkultur' },
    { text: 'Pikachu', category: 'Popkultur' },
    { text: 'riddler', category: 'Popkultur' },
    { text: 'rugrats', category: 'Popkultur' },
    { text: 'Twoface', category: 'Popkultur' },
    { text: 'avatar', category: 'Popkultur' },
    { text: 'barbie', category: 'Popkultur' },
    { text: 'batman', category: 'Popkultur' },
    { text: 'Die Maus', category: 'Popkultur' },
    { text: 'bowser', category: 'Popkultur' },
    { text: 'Legend of Zelda', category: 'Popkultur' },
    { text: 'Mickey Mouse', category: 'Popkultur' },
    { text: 'Voldemort', category: 'Popkultur' },
    { text: 'Conan der Barbar', category: 'Popkultur' },
    { text: 'Die Simpsons', category: 'Popkultur' },
    { text: 'Rick & Morty', category: 'Popkultur' },
    { text: 'Kermit', category: 'Popkultur' },
    { text: 'Spongebob', category: 'Popkultur' },
    { text: 'Simba', category: 'Popkultur' },
	{ text: 'Scooby Doo', category: 'Popkultur' },

    { text: 'Künstler', category: 'Beruf' },
    { text: 'Meuchelmörder', category: 'Beruf' },
    { text: 'Barbier', category: 'Beruf' },
    { text: 'Metzger', category: 'Beruf' },
    { text: 'Kapitän', category: 'Beruf' },
    { text: 'Kassierer', category: 'Beruf' },
	{ text: 'Koch', category: 'Beruf' },
	{ text: 'Clown', category: 'Beruf' },
	{ text: 'Koch', category: 'Beruf' },
    { text: 'Zahnarzt', category: 'Beruf' },
    { text: 'DJ', category: 'Beruf' },
    { text: 'Arzt', category: 'Beruf' },
    { text: 'Schlagzeuger', category: 'Beruf' },
    { text: 'Landwirt', category: 'Beruf' },
    { text: 'Feuerwehrmann', category: 'Beruf' },
	{ text: 'Hacker', category: 'Beruf' },
    { text: 'Gangster', category: 'Beruf' },
    { text: 'Gärtner', category: 'Beruf' },
    { text: 'Turner', category: 'Beruf' },
    { text: 'Hausmeister', category: 'Beruf' },
	{ text: 'Rechtsanwalt', category: 'Beruf' },
    { text: 'Zauberer', category: 'Beruf' },
    { text: 'Postbote', category: 'Beruf' },
    { text: 'Milkman', category: 'Beruf' },
    { text: 'Filmregisseur', category: 'Beruf' },
    { text: 'Opernsänger', category: 'Beruf' },
    { text: 'Maler', category: 'Beruf' },
	{ text: 'Pilot', category: 'Beruf' },
    { text: 'Klempner', category: 'Beruf' },
    { text: 'Polizist', category: 'Beruf' },
    { text: 'Poolboy', category: 'Beruf' },
    { text: 'Priester', category: 'Beruf' },
    { text: 'Prinzessin', category: 'Beruf' },
    { text: 'Sheriff', category: 'Beruf' },
    { text: 'Soldat', category: 'Beruf' },
    { text: 'Chirurg', category: 'Beruf' },
    { text: 'Lehrer', category: 'Beruf' },
    { text: 'Lehrer', category: 'Beruf' },
    { text: 'Kellner', category: 'Beruf' },
    { text: 'Krieger', category: 'Beruf' },
    { text: 'Fensterputzer', category: 'Beruf' },
    { text: 'Wrestler', category: 'Beruf' },

    { category: 'Tier', text: 'Erdferkel' },
    { category: 'Tier', text: 'Alpaka' },
    { category: 'Tier', text: 'Ameise' },
    { category: 'Tier', text: 'Ameisenbär' },
    { category: 'Tier', text: 'Gürteltier' },
    { category: 'Tier', text: 'Pavian' },
    { category: 'Tier', text: 'Dachs' },
	{ category: 'Tier', text: 'Fledermaus' },
    { category: 'Tier', text: 'Bär' },
    { category: 'Tier', text: 'Biber' },
    { category: 'Tier', text: 'Biene' },
    { category: 'Tier', text: 'Vogel' },
    { category: 'Tier', text: 'Büffel' },
    { category: 'Tier', text: 'Stier' },
    { category: 'Tier', text: 'Kalb' },
    { category: 'Tier', text: 'Kamel' },
    { category: 'Tier', text: 'Katze' },
    { category: 'Tier', text: 'Raupe' },
	{ category: 'Tier', text: 'Wels' },
	{ category: 'Tier', text: 'Chamäleon' },
    { category: 'Tier', text: 'Gepard' },
    { category: 'Tier', text: 'Huhn' },
    { category: 'Tier', text: 'Schimpanse' },
    { category: 'Tier', text: 'Chihuahua' },
    { category: 'Tier', text: 'Zikade ' },
	{ category: 'Tier', text: 'Kakerlake' },
    { category: 'Tier', text: 'Kuh' },
    { category: 'Tier', text: 'Kranich' },
	{ category: 'Tier', text: 'Krabbe' },
    { category: 'Tier', text: 'Grille' },
    { category: 'Tier', text: 'Krokodil' },
    { category: 'Tier', text: 'Hirsch' },
    { category: 'Tier', text: 'Dinosaurier' },
    { category: 'Tier', text: 'Hund' },
    { category: 'Tier', text: 'Delphin' },
    { category: 'Tier', text: 'Esel' },
    { category: 'Tier', text: 'Ente' },
	{ category: 'Tier', text: 'Libelle' },
    { category: 'Tier', text: 'Adler' },
    { category: 'Tier', text: 'Elefant' },
	{ category: 'Tier', text: 'Glühwürmchen' },
    { category: 'Tier', text: 'Fisch' },
    { category: 'Tier', text: 'Flamingo' },
    { category: 'Tier', text: 'Fliege' },
    { category: 'Tier', text: 'Fuchs' },
    { category: 'Tier', text: 'Frosch' },
    { category: 'Tier', text: 'Giraffe' },
    { category: 'Tier', text: 'Ziege' },
    { category: 'Tier', text: 'Goldfisch' },
	{ category: 'Tier', text: 'Gans' },
    { category: 'Tier', text: 'Gorilla' },
    { category: 'Tier', text: 'Grashüpfer' },
    { category: 'Tier', text: 'Hamster' },
    { category: 'Tier', text: 'Nilpferd' },
    { category: 'Tier', text: 'Pferd' },
    { category: 'Tier', text: 'Hyäne' },
    { category: 'Tier', text: 'Jaguar' },
    { category: 'Tier', text: 'Känguru' },
    { category: 'Tier', text: 'Kätzchen' },
    { category: 'Tier', text: 'Marienkäfer' },
    { category: 'Tier', text: 'Leopard' },
    { category: 'Tier', text: 'Löwe' },
    { category: 'Tier', text: 'Eidechse' },
    { category: 'Tier', text: 'Lama' },
    { category: 'Tier', text: 'Hummer' },
    { category: 'Tier', text: 'Mammut' },
    { category: 'Tier', text: 'Affe' },
    { category: 'Tier', text: 'Moskito' },
	{ category: 'Tier', text: 'Elch' },
    { category: 'Tier', text: 'Maus' },
    { category: 'Tier', text: 'Einhornwal' },
    { category: 'Tier', text: 'Oktopus' },
    { category: 'Tier', text: 'Strauß' },
    { category: 'Tier', text: 'Otter' },
    { category: 'Tier', text: 'Eule' },
    { category: 'Tier', text: 'Otter' },
    { category: 'Tier', text: 'Eule' },
    { category: 'Tier', text: 'Auster' },
    { category: 'Tier', text: 'Panda' },
    { category: 'Tier', text: 'Schuppentier' },
	{ category: 'Tier', text: 'Papagei' },
    { category: 'Tier', text: 'Panther' },
    { category: 'Tier', text: 'Pfau' },
    { category: 'Tier', text: 'Pelikan' },
    { category: 'Tier', text: 'Pinguin' },
    { category: 'Tier', text: 'Schwein' },
    { category: 'Tier', text: 'Taube' },
	{ category: 'Tier', text: 'Pitbull' },
	{ category: 'Tier', text: 'Schnabeltier' },
    { category: 'Tier', text: 'Stachelschwein' },
	{ category: 'Tier', text: 'Pudel' },
    { category: 'Tier', text: 'Welpe' },
    { category: 'Tier', text: 'Kaninchen' },
    { category: 'Tier', text: 'Waschbär' },
    { category: 'Tier', text: 'Ratte' },
    { category: 'Tier', text: 'Rentier' },
	{ category: 'Tier', text: 'Reptil' },
    { category: 'Tier', text: 'Nashorn' },
    { category: 'Tier', text: 'Hahn' },
    { category: 'Tier', text: 'Skorpion' },
    { category: 'Tier', text: 'Möwe' },
    { category: 'Tier', text: 'Seepferdchen' },
    { category: 'Tier', text: 'Seehund' },
    { category: 'Tier', text: 'Hai' },
    { category: 'Tier', text: 'Schaf' },
    { category: 'Tier', text: 'Garnele' },
	{ category: 'Tier', text: 'Stinktier' },
    { category: 'Tier', text: 'Schnecke' },
    { category: 'Tier', text: 'Schlange' },
    { category: 'Tier', text: 'Spinne' },
    { category: 'Tier', text: 'Tintenfisch' },
    { category: 'Tier', text: 'Eichhörnchen' },
    { category: 'Tier', text: 'Seestern' },
    { category: 'Tier', text: 'Storch' },
    { category: 'Tier', text: 'Schwan' },
    { category: 'Tier', text: 'Kaulquappe' },
    { category: 'Tier', text: 'Tiger' },
    { category: 'Tier', text: 'Kröte' },
    { category: 'Tier', text: 'tropischer Fisch' },
    { category: 'Tier', text: 'Thunfisch' },
    { category: 'Tier', text: 'Truthahn' },
    { category: 'Tier', text: 'Schildkröte' },
    { category: 'Tier', text: 'Schildkröte' },
	{ category: 'Tier', text: 'Geier' },
	{ category: 'Tier', text: 'Walross' },
    { category: 'Tier', text: 'Wal' },
    { category: 'Tier', text: 'Wolf' },
    { category: 'Tier', text: 'Wombat' },
    { category: 'Tier', text: 'Wurm' },
	{ category: 'Tier', text: 'Zebra' },

    { text: 'Speck', category: 'Lebensmittel' },
    { text: 'Baguette', category: 'Lebensmittel' },
    { text: 'Barbeque', category: 'Lebensmittel' },
    { text: 'Bohnen', category: 'Lebensmittel' },
    { text: 'Bier', category: 'Lebensmittel' },
    { text: 'Burrito', category: 'Lebensmittel' },
	{ text: 'Torte', category: 'Lebensmittel' },
    { text: 'Müsli', category: 'Lebensmittel' },
    { text: 'Champagner', category: 'Lebensmittel' },
    { text: 'Käse', category: 'Lebensmittel' },
    { text: 'Chicken Wings', category: 'Lebensmittel' },
    { text: 'Kaffee', category: 'Lebensmittel' },
    { text: 'Corndog', category: 'Lebensmittel' },
	{ text: 'Croissant', category: 'Lebensmittel' },
    { text: 'Cupcake', category: 'Lebensmittel' },
    { text: 'Frühlingsrolle', category: 'Lebensmittel' },
    { text: 'Espresso', category: 'Lebensmittel' },
    { text: 'Fast Food', category: 'Lebensmittel' },
    { text: 'Fisch und Chips', category: 'Lebensmittel' },
    { text: 'Zuckerguss', category: 'Lebensmittel' },
	{ text: 'Hamburger', category: 'Lebensmittel' },
    { text: 'Schinkenknochen', category: 'Lebensmittel' },
    { text: 'Hamwich', category: 'Lebensmittel' },
    { text: 'Scharfe Soße', category: 'Lebensmittel' },
    { text: 'Junk Food', category: 'Lebensmittel' },
    { text: 'Kebab', category: 'Lebensmittel' },
	{ text: 'Ketchup', category: 'Lebensmittel' },
	{ text: 'Lasagna', category: 'Lebensmittel' },
    { text: 'Limonade', category: 'Lebensmittel' },
    { text: 'Makkaroni', category: 'Lebensmittel' },
    { text: 'Martini', category: 'Lebensmittel' },
    { text: 'Kartoffelpüree', category: 'Lebensmittel' },
    { text: 'Fleischbällchen', category: 'Lebensmittel' },
	{ text: 'Milch', category: 'Lebensmittel' },
    { text: 'Pilz', category: 'Lebensmittel' },
    { text: 'Senf', category: 'Lebensmittel' },
    { text: 'Nudeln', category: 'Lebensmittel' },
    { text: 'Haferflocken', category: 'Lebensmittel' },
    { text: 'Pfannkuchen', category: 'Lebensmittel' },
    { text: 'Nudeln', category: 'Lebensmittel' },
    { text: 'Kuchen', category: 'Lebensmittel' },
    { text: 'Pizza', category: 'Lebensmittel' },
    { text: 'Popcorn', category: 'Lebensmittel' },
    { text: 'Brezel', category: 'Lebensmittel' },
    { text: 'Kürbis', category: 'Lebensmittel' },
    { text: 'Salat', category: 'Lebensmittel' },
    { text: 'Sandwich', category: 'Lebensmittel' },
    { text: 'Würstchen', category: 'Lebensmittel' },
    { text: 'Meeresfrüchte', category: 'Lebensmittel' },
    { text: 'Smoothie', category: 'Lebensmittel' },
    { text: 'Snowcone', category: 'Lebensmittel' },
    { text: 'Sojasoße', category: 'Lebensmittel' },
    { text: 'Sushi', category: 'Lebensmittel' },
    { text: 'Tee', category: 'Lebensmittel' },
    { text: 'Tequila', category: 'Lebensmittel' },
	{ text: 'Waffeln', category: 'Lebensmittel' },
    { text: 'Whiskey', category: 'Lebensmittel' },



    { text: 'Horror', category: 'Film Genres' },
    { text: 'Action', category: 'Film Genres' },
    { text: 'Thriller', category: 'Film Genres' },
    { text: 'Sci-Fi', category: 'Film Genres' },
    { text: 'Rom-Com', category: 'Film Genres' },
    { text: 'Western', category: 'Film Genres' },
    { text: 'Komödie', category: 'Film Genres' },
    { text: 'Gangster', category: 'Film Genres' },
    { text: 'Slapstick', category: 'Film Genres' },
    { text: 'Krieg', category: 'Film Genres' },
    { text: 'Dokumentarfilm', category: 'Film Genres' },
    { text: 'Mockumentry', category: 'Film Genres' },
    { text: 'Musical', category: 'Film Genres' },
    { text: 'Animation', category: 'Film Genres' },
    { text: 'Katastrophenfilm', category: 'Film Genres' },
    { text: 'Zombies', category: 'Film Genres' },
    { text: 'Sport', category: 'Film Genres' },

    { text: 'A Clockwork Orange', category: 'Filme' },
	{ text: 'Armagedon', category: 'Filme' },
    { text: 'Alien', category: 'Filme' },
    { text: 'Austin Powers', category: 'Filme' },
    { text: 'Avengers', category: 'Filme' },
    { text: 'Zurück in die Zukunft', category: 'Filme' },
    { text: 'Braveheart', category: 'Filme' },
	{ text: 'Beetlejuice', category: 'Filme' },
    { text: 'Stirb langsam', category: 'Filme' },
    { text: 'E.T.', category: 'Filme' },
    { text: 'Fargo', category: 'Filme' },
    { text: 'Finding Nemo', category: 'Filme' },
    { text: 'Forrest Gump', category: 'Filme' },
	{ text: 'Frozen', category: 'Filme' },
    { text: 'Gladiator', category: 'Filme' },
    { text: 'Golden Eye', category: 'Filme' },
    { text: 'Vom Winde verweht', category: 'Filme' },
    { text: 'Murmeltiertag', category: 'Filme' },
    { text: 'Home Alone', category: 'Filme' },
    { text: 'Inception', category: 'Filme' },
    { text: 'Indiana Jones', category: 'Filme' },
    { text: 'Inglourious Basterds', category: 'Filme' },
    { text: 'Der weiße Hai', category: 'Filme' },
    { text: 'Jurassic Park', category: 'Filme' },
    { text: 'King Kong', category: 'Filme' },
    { text: 'König der Löwen', category: 'Filme' },
    { text: 'Mary Poppins', category: 'Filme' },
    { text: 'Minority Report', category: 'Filme' },
    { text: 'Mission Impossible', category: 'Filme' },
    { text: 'Monty Python und der Heilige Gral', category: 'Filme' },
    { text: 'Pulp Fiction', category: 'Filme' },
    { text: 'Rocky Horror Picture Show', category: 'Filme' },
    { text: 'Rocky', category: 'Filme' },
    { text: 'Saving Private Ryan', category: 'Filme' },
    { text: 'Scarface', category: 'Filme' },
    { text: 'Shrek', category: 'Filme' },
    { text: 'Star Wars', category: 'Filme' },
    { text: 'Terminator', category: 'Filme' },
    { text: 'The Good, the Bad and the Ugly', category: 'Filme' },
    { text: 'The Green Mile', category: 'Filme' },
    { text: 'Der Herr der Ringe', category: 'Filme' },
    { text: 'The Matrix', category: 'Filme' },
    { text: 'Die Verurteilten', category: 'Filme' },
    { text: 'The Social Network', category: 'Filme' },
    { text: 'Der Zauberer von Oz', category: 'Filme' },
    { text: 'Titanic', category: 'Filme' },
    { text: 'Toy Story', category: 'Filme' },
    { text: 'West Side Story', category: 'Filme' },
    { text: 'Wonder Woman', category: 'Filme' },
    { text: 'X-Men', category: 'Filme' },
	{ text: 'Robocop', category: 'Filme' },


    { text: 'Saures Bonbon', category: 'Snacks' },
    { text: 'Twinkie', category: 'Snacks' },
    { text: 'Lollipop', category: 'Snacks' },
    { text: 'Eis am Stiel', category: 'Snacks' },
    { text: 'Skittles', category: 'Snacks' },
    { text: 'Brownie', category: 'Snacks' },
    { text: 'Cookie', category: 'Snacks' },
    { text: 'Doritos', category: 'Snacks' },
    { text: 'Saures Bonbon', category: 'Snacks' },
    { text: 'Eiscreme', category: 'Snacks' },

    { text: 'Die Pyramiden', category: 'Berühmtes Wahrzeichen' },
    { text: 'Christus der Erlöser-Statue', category: 'Berühmtes Wahrzeichen' },
    { text: 'Die Große Chinesische Mauer', category: 'Berühmtes Wahrzeichen' },
    { text: 'Schiefer Turm von Pisa', category: 'Berühmtes Wahrzeichen' },
    { text: 'Empire State Building', category: 'Berühmtes Wahrzeichen' },
    { text: 'Kolosseum', category: 'Berühmtes Wahrzeichen' },
    { text: 'Der Eiffelturm', category: 'Berühmtes Wahrzeichen' },
    { text: 'Freiheitsstatue', category: 'Berühmtes Wahrzeichen' },
    { text: 'Die Sphinx', category: 'Berühmtes Wahrzeichen' },
    { text: 'Die kleine Meerjungfrau', category: 'Berühmtes Wahrzeichen' },
    { text: 'Das Taj Mahal', category: 'Berühmtes Wahrzeichen' },
    { text: 'Big Ben', category: 'Berühmtes Wahrzeichen' },
    { text: 'Loch Ness', category: 'Berühmtes Wahrzeichen' },
    { text: 'Brandenburger Tor', category: 'Berühmtes Wahrzeichen' },
    { text: 'Akropolis', category: 'Berühmtes Wahrzeichen' },
    { text: 'Stonehenge', category: 'Berühmtes Wahrzeichen' },
    { text: 'Osterinsel', category: 'Berühmtes Wahrzeichen' },
    { text: 'Capitol Hill', category: 'Berühmtes Wahrzeichen' },
    { text: 'Niagra Falls', category: 'Berühmtes Wahrzeichen' },
    { text: 'Mount Rushmore', category: 'Berühmtes Wahrzeichen' },
    { text: 'Grand Canyon', category: 'Berühmtes Wahrzeichen' },
    { text: 'Fontana de Trevi', category: 'Berühmtes Wahrzeichen' },
    { text: 'Sydney Opera House', category: 'Berühmtes Wahrzeichen' },
    { text: 'Golden Gate Bridge', category: 'Berühmtes Wahrzeichen' },
    { text: 'Die Verbotene Stadt', category: 'Berühmtes Wahrzeichen' },
    { text: 'Der Kreml', category: 'Berühmtes Wahrzeichen' },
    { text: 'Der Louvre', category: 'Berühmtes Wahrzeichen' },
    { text: 'Das Hollywood-Zeichen ', category: 'Berühmtes Wahrzeichen' },

    { text: 'Cinderella', category: 'Märchen' },
    { text: 'Die drei kleinen Schweinchen', category: 'Märchen' },
    { text: 'Das hässliche Entlein', category: 'Märchen' },
    { text: 'Die Prinzessin auf der Erbse', category: 'Märchen' },
    { text: 'Däumelinchen', category: 'Märchen' },
    { text: 'Die kleine Meerjungfrau', category: 'Märchen' },
    { text: 'Däumelinchen', category: 'Märchen' },
    { text: "Des Kaisers neue Kleider", category: 'Märchen' },
    { text: 'Dornröschen', category: 'Märchen' },
    { text: 'Schneewittchen', category: 'Märchen' },
    { text: 'Rapunzel', category: 'Märchen' },
    { text: 'Der Froschkönig', category: 'Märchen' },
    { text: 'Hänsel und Gretel', category: 'Märchen' },
    { text: 'Rumpelstilzchen', category: 'Märchen' },
    { text: 'Die goldene Gans', category: 'Märchen' },
    { text: 'Der gestiefelte Kater', category: 'Märchen' },
    { text: 'Aladdin', category: 'Märchen' },
    { text: 'Die Schöne und das Biest', category: 'Märchen' },
    { text: 'Ali Baba und die vierzig Räuber', category: 'Märchen' },
    { text: 'Sindbad', category: 'Märchen' },

];

function getRandomWord(lang = 'en', category = null) {
  const wordList = words[lang] || words.en;
  const filteredList = category ? wordList.filter(word => word.category === category) : wordList;
  return filteredList[Math.floor(Math.random() * filteredList.length)];
}

module.exports = {
  words,
  getRandomWord,
};
